woowacourse-teams/2022-pickpick

.gitignore
- .DS_Store gitignore 추가
- Closes #7
=> chore: global .gitignore 파일 추가

frontend/package-lock.json, frontend/package.json, frontend/src/api/messages.ts, frontend/src/index.tsx, frontend/src/pages/Home/index.tsx
react-query 적용
- error, loading 처리 추가
- useEffect 내부 로직 useQuery로 변경
- Closes #36
=> refactor: React-Query 적용하여 API 연동

frontend/src/components/ProfileImage/style.ts
유저 프로필 이미지 border-radius 추가
유저 프로필 이미지 border-radius 추가
- Closes #45
=> fix: 유저 프로필 이미지 border-radius 추가

frontend/src/@utils/index.ts, frontend/src/components/MessageCard/index.tsx
서버에서 받아온 메시지 작성일 가공
- parseDate, getTimeStandard util 함수 작성
- Closes #35
=> fix: 서버에서 받아온 메시지 작성일 가공

frontend/src/components/MessageCard/index.tsx, frontend/src/components/MessageCard/style.ts, frontend/src/components/SearchInput/style.ts, frontend/src/pages/Home/index.tsx, frontend/src/pages/Home/style.ts
MessageCard component UI 반응형 구현
MessageCard component UI 반응형 구현
- Closes #47
=> fix: MessageCard component UI 반응형 구현

frontend/src/components/MessageCardSkeleton/index.stories.js, frontend/src/components/MessageCardSkeleton/index.tsx, frontend/src/components/MessageCardSkeleton/style.ts, frontend/src/pages/Home/index.tsx
- Skeleton Component 작성 및 적용
- MessageCardSkeleton component 개발
- Home page Loading 상태 UI 변경
- 기존 div tag -> skeleton ui로 변경
- Closes #54
=> feat: Skeleton Component 작성 및 적용

frontend/package-lock.json, frontend/package.json, frontend/src/@types/shared.ts, frontend/src/api/index.ts, frontend/src/api/messages.ts, frontend/src/pages/Home/index.tsx
- API fetch Axios 적용
- axios install
- ResponseMessages, Message type shared.ts로 이동
- fetch 메서드 axios로 변경
- Closes #62
=> refactor: API fetch Axios 적용

frontend/src/@types/shared.ts, frontend/src/api/messages.ts, frontend/src/components/@shared/InfiniteScroll/index.tsx, frontend/src/mocks/data/index.ts, frontend/src/mocks/handlers.ts, frontend/src/pages/Home/index.tsx
- Home page 무한 스크롤 구현
- InfiniteScroll component 생성 및 Home page 적용
- mock data 추가
- getMessages API 수정
- ResponseMessages type 추가
- MSW message handler 수정
- getMessages API 수정
- InfiniteScroll 적용
- useQuery => useInfiniteQuery로 변경
- Closes #33
=> feat: 무한 스크롤 구현

frontend/src/components/MessageCardSkeleton/index.tsx, frontend/src/components/MessageCardSkeleton/style.ts
- MessageCardSkeleton UI 수정
<br><br>
- firstLineSkeleton -> LongLineSkeleton으로 변수명 변경
- secondLineSkeleton -> shortLineSkeleton으로 변수명 변경
<br><br>
- Close #69 
<br><br>
=> refactor: MessageCardSkeleton UI 수정

frontend/src/pages/Home/index.tsx
- useInfiniteQuery에서 반환되는 Messages 가공 함수 수정
- reduceMessages -> extractMessages로 함수명 수정
- reduce -> flatMap으로 변경
<br><br>
[mdn-flatMap](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap)
<br><br>
- Close #72 
<br><br>
=> refactor: useInfiniteQuery에서 반환되는 Messages 가공 함수 수정

frontend/src/@styles/GlobalStyle.ts, frontend/src/components/layouts/LayoutContainer/index.tsx, frontend/src/index.tsx, frontend/src/pages/AddChannel/index.tsx, frontend/src/pages/AddChannel/style.ts
채널 선택 page UI 구현
- 채널 선택 페이지 구현 
- 채널 선택 페이지 라우팅 연결
- GlobalStyle 수정 
- Close #56
=> feat: 채널 선택 page UI 구현

frontend/src/api/messages.ts, frontend/src/components/@shared/Dimmer/style.ts, frontend/src/components/Drawer/style.ts, frontend/src/components/Dropdown/index.tsx, frontend/src/components/DropdownMenu/index.tsx, frontend/src/index.tsx, frontend/src/mocks/data/index.ts, frontend/src/mocks/handlers.ts, frontend/src/pages/Feed/index.tsx
각 날짜에 맞는 Message 그룹핑 구현 및 Dropdown Menu Option 구현
<br><br>
- dimmer, drawer UI 포지션 변경
- 페이지 진입시 재렌더링 되는 문제 해결
- mocking data, handlers 수정
- 각 날짜에 맞는 메시지 그룹핑 구현
- 각 날짜에 맞는 dropdown menu option 구현
<br><br>
- Close #88 
<br><br>
=> feat: 각 날짜에 맞는 Message 그룹핑 구현 및 Dropdown Menu Option 구현

frontend/src/mocks/data/index.ts, frontend/src/mocks/handlers.ts
- MSW API 모킹 
- Mesages 조회 API 모킹 수정 
- 전체 채널 목록 조회 API 모킹
- 구독한 채널 목록 조회 API 모킹 
- 채널 구독 추가 및 제거 API 는 추후 변경가능성이 있다고 판단되어 아직 모킹하지 않았습니다.
- Close #85 
<br><br>
=> MSW API 모킹

frontend/src/api/messages.ts, frontend/src/mocks/data/index.ts, frontend/src/mocks/handlers.ts, frontend/webpack.common.js
MSW API 모킹 수정
<br><br>
MSW API 모킹 수정
<br><br>
- Close #93 
<br><br>
=> fix: MSW API 모킹 수정

backend/src/main/java/com/pickpick/controller/ChannelSubscriptionController.java, backend/src/main/java/com/pickpick/controller/dto/ChannelOrderRequest.java, backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionRequest.java, backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionResponse.java, backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionResponses.java, backend/src/main/java/com/pickpick/entity/ChannelSubscription.java, backend/src/main/java/com/pickpick/exception/ChannelNotFoundException.java, backend/src/main/java/com/pickpick/exception/MemberNotFoundException.java, backend/src/main/java/com/pickpick/exception/SlackEventNotFoundException.java, backend/src/main/java/com/pickpick/repository/ChannelRepository.java, backend/src/main/java/com/pickpick/repository/ChannelSubscriptionRepository.java, backend/src/main/java/com/pickpick/repository/MemberRepository.java, backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java
채널 구독 및 api 추가를 main에 반영  
<br>
branch merge 순서가 꼬여서 리뷰 해주셨던 채널 구독 api pr을 다시 올렸습니다 🥲 
이미 리뷰 받은 내역이라 충돌 해결 후 셀프로 머지합니다  
<br>
=> feat: 채널 구독 및 api 추가를 main에 반영  

frontend/src/@constants/index.ts, frontend/src/App.tsx, frontend/src/Routes.tsx, frontend/src/components/@shared/WrapperButton/style.ts, frontend/src/components/@shared/WrapperLink/index.tsx, frontend/src/components/@shared/WrapperLink/style.ts, frontend/src/components/layouts/LayoutContainer/index.tsx, frontend/src/components/layouts/Navigation/index.tsx, frontend/src/index.tsx, frontend/src/pages/Alarm/index.tsx, frontend/src/pages/Bookmark/index.tsx, frontend/src/pages/NotFound/index.tsx
-  Navigation 페이지 라우팅 구현
-  WrapperLink Component 작성 및 네비게이션에 적용
-  useRoutes 적용
- App.tsx 로 분리하여 라우팅 적용 
- Routes 파일 생성 
- 네비게이션 바에 올바른 네비게이팅 적용
<br><br>
- Close #59 
<br><br>
=> feat: Navigation 페이지 라우팅 구현

frontend/src/pages/SpecificDateFeed/index.tsx
스크롤 이벤트 개선
<br><br>
- 스크롤 이벤트 unmount시 제거
<br><br>
- Close #115 
<br><br>
=> refactor: 스크롤 이벤트 unmount시 제거

backend/src/main/java/com/pickpick/config/CorsConfig.java
- CORS 대응
<br><br>
- config 패키지 추가
- CorsConfig 클래스 추가
- 현재는 전체 URL, 전체 메서드에 대해 개방하였습니다. 장바구니 미션에서 제공된 코드를 재사용했습니다.
- 이 부분에 대해선 다음 스프린트에서 디테일 잡아보시죠!
<br><br>
- Close #113 
<br><br>
=> fix: CORS 대응

frontend/src/components/Drawer/style.ts, frontend/src/components/layouts/Navigation/style.ts
Navigation component 높이 수정
<br><br>
Navigation component 높이 수정
<br><br>
- Close #131 
<br><br>
=> refactor: Navigation component 높이 수정

frontend/tsconfig.json
tsconfig 수정
tsconfig 내 jsxdev -> jsx 로 수정
=> hotfix: tsconfig 수정

.gitmodules, backend/Jenkinsfile, backend/src/main/resources/application.yml
서브모듈과 젠킨스 파일 추가
- 서브모듈로 `application.yml`을 추가했습니다
- `main` 브랜치에 `push` 이벤트가 발생하면 이제 `aws`에 자동 배포가 됩니다     
서브모듈 `yml` DB 설정에 누구의 스키마를 연결할 지 논의가 필요할 것 같습니다  
현재는 봄 걸로 되어있어요  
- Close #40 
- Close #134 
<br>
=> chore: 서브모듈과 젠킨스 파일 추가

frontend/webpack.common.js, frontend/webpack.dev.js
- 웹팩 설정 수정
- historyApiFallback 설정 common 으로 이동
=> chore: 웹팩 설정 수정

frontend/src/components/layouts/Navigation/index.tsx, frontend/src/pages/AddChannel/index.tsx, frontend/src/pages/Home/index.tsx
- 라우팅 상태에 따라 Navigation 아이콘 focus 상태 수정
- 라우팅 상태에 따라 Navigation 아이콘 색상 수정
- 시작하기 버튼 클릭 시 임시로 navigation 하도록 구현 
- addChannel 페이지로 navigation - addChannel 페이지에 다음 버튼 임시 추가
- Close #139 
<br><br>
=> feat: 라우팅 상태에 따라 Navigation 아이콘 focus 상태 수정

frontend/src/components/MessageCard/index.tsx
- MessageCard UI 변경
<br><br>
- 삭제 버튼 제거
- 즐겨찾기 text 변경 (삭제 -> 즐겨찾기)
<br><br>
- Close #144 
<br><br>
=> style: MessageCard UI 변경

backend/src/main/java/com/pickpick/controller/ControllerAdvice.java, backend/src/main/java/com/pickpick/controller/event/SlackEvent.java, backend/src/main/java/com/pickpick/exception/BadRequestException.java, backend/src/main/java/com/pickpick/exception/ChannelNotFoundException.java, backend/src/main/java/com/pickpick/exception/MemberNotFoundException.java, backend/src/main/java/com/pickpick/exception/MessageNotFoundException.java, backend/src/main/java/com/pickpick/exception/NotFoundException.java, backend/src/main/java/com/pickpick/exception/SlackEventNotFoundException.java, backend/src/main/java/com/pickpick/exception/SlackEventServiceNotFoundException.java, backend/src/main/java/com/pickpick/exception/SubscriptionDuplicatedException.java, backend/src/main/java/com/pickpick/exception/SubscriptionNotExistException.java, backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java, backend/src/main/java/com/pickpick/service/MessageCreatedService.java, backend/src/main/java/com/pickpick/service/MessageService.java, backend/src/main/java/com/pickpick/service/SlackEventServiceFinder.java
Exception 관련 처리
<br><br>
- 커밋1 : 메시지에 Exception 발생 원인이 되는 데이터 추가
- 커밋2 : Exception 계층화 적용
<br><br>
브랜치는 잘못 만들어서 fork한 레포지토리에 생성됐는데 무시해주세요😅
커밋2의 Exception 계층화는 이전에 회의에서 말씀드렸던 구조를 적용해보았습니다.
_(다들 좋다는 의견이었으나 나중으로 우선 순위가 밀렸던 사항)_
디테일한 이름이나 어떤 status code를 반환하는지에 대해서는 회의가 필요할 것 같습니다.
두번째 커밋은 이야기 나눈 후에 다른 식으로 계층화하고 싶다던가 등의 의견이 나온다면 롤백하고 커밋1만 적용하는 방향으로 가도 괜찮을 것 같아요🙂
<br><br>
=> refactor: Exception 관련 처리

frontend/src/pages/SpecificDateFeed/index.tsx
- 무한 스크롤 관련 버그 수정
<br><br>
- query keys에 동적으로 queryKey 할당
<br><br>
- Close #147 
<br><br>
=> fix: 무한 스크롤 관련 버그 수정

frontend/src/@types/shared.ts, frontend/src/api/channels.ts, frontend/src/components/Drawer/index.tsx, frontend/src/components/layouts/Navigation/index.tsx, frontend/src/pages/AddChannel/index.tsx
채널 추가 페이지 채널 목록 API 연동
- 채널 목록 조회 API 연결
- 채널 구독 API 연결
- 채널 구독 취소 API 연결 
- 조회 (GET)는 잘 동작하는데, 구독(POST)과 구독취소(DELETE) 는 서버에서 404 에러가 뜨네요 . 내일 아침 이 부분 수정되는대로 WIP 풀겠습니다.
- Close #151 
<br><br>
=> feat: 채널 추가 페이지 채널 목록 API 연동

backend/Jenkinsfile
Jenkinsfile 스타일 개선
<br><br>
- 중괄호 시작 선언 위치 표준화
- 복수 라인의 쉘 스크립트 가독성 개선
- 작업단위 별 구분 개행 추가
<br><br>
- 단순 스타일 변경이어서 이슈는 생성하지 않았습니다.
- 의견 나눠보면 좋을 것 같네요.
<br><br>
=> style: Jenkinsfile 스타일 개선

backend/src/main/java/com/pickpick/exception/SubscriptionDuplicateException.java, backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java, backend/src/test/java/com/pickpick/controller/event/SlackEventTest.java, backend/src/test/java/com/pickpick/service/ChannelSubscriptionServiceTest.java
채널 구독에 대한 서비스 테스트 추가
채널 구독에 대한 서비스 테스트 부분이 미흡하여 테스트 추가했습니다.
- ChannelSubscriptionService 쪽에 사용하지 않는 메서드가 있어 삭제했습니다.
- 서비스에 대한 테스트를 추가한 것이어서, 가볍게 봐주시면 될 것 같아요 😊
<br><br>
=> test: 채널 구독에 대한 서비스 테스트 추가

frontend/src/@utils/index.ts, frontend/src/api/utils.ts, frontend/src/components/@shared/InfiniteScroll/index.tsx, frontend/src/components/DateDropdown/index.tsx, frontend/src/components/DateDropdown/style.ts, frontend/src/components/MessagesLoadingStatus/index.tsx, frontend/src/hooks/useIntersectionObserver.ts, frontend/src/hooks/useMessageDate.ts, frontend/src/hooks/useTopScreenEventHandlers.ts, frontend/src/pages/Feed/index.tsx, frontend/src/pages/Feed/style.ts, frontend/src/pages/SpecificDateFeed/index.tsx
- 양방향 무한 스크롤 로직 리팩토링 및 Feed Page 리팩토링
-  useMessageDate Hook 분리 및 적용
-  infinte query callback 분리 및 적용
- MessagesLoadingStatus 컴포넌트 분리 및 적용
- extractResponseMessages 함수 분리 및 적용
- useTopScreenEventHandlers Hook 분리 및 적용 
<br><br>
- Close #99 
<br><br>
=> refactor: 양방향 무한 스크롤 로직 리팩토링 및 Feed Page 리팩토링

frontend/src/@constants/index.ts
url pathname 케밥케이스 적용
`/addChannel` -> `/add-channel` 로 수정
- Close #191 
<br><br>
=> refactor: url pathname 케밥케이스 적용

backend/Jenkinsfile, backend/src/docs/asciidoc/api.adoc
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> hotfix: jenkinsfile 수정

frontend/src/@constants/index.ts, frontend/src/api/channels.ts, frontend/src/components/@layouts/Navigation/index.tsx, frontend/src/pages/AddChannel/index.tsx
채널 목록 조회 API Endpoint 수정 
- 채널 목록 조회 API Endpoint 수정
- Bearer 임시 토큰 수정  
- Drawer Open 시 refetch 
<br><br>
=> hotfix: 채널 목록 조회 API Endpoint 수정 

frontend/src/components/ErrorBoundary/index.tsx, frontend/src/index.tsx, frontend/src/pages/UnexpectedError/index.tsx
error boundary 구현
<br><br>
- ErrorBoundary component 개발
- UnexpectedError component 개발
- ErrorBoundary, UnexpectedError component 적용
<br><br>
- Close #43 
<br><br>
=> feat: error boundary 구현

.gitmodules, backend/.gitignore, backend/src/test/resources/application.yml
테스트용 yml 서브모듈 적용
<br>
1. 서브모듈로 H2를 사용하는 테스트용 `yml`을 추가했습니다  
2. 서브모듈 적용을 위해 `.gitignore`에서 `application.yml`을 제외시켰습니다  
<br>
💥 **로컬 application.yml과 충돌이 발생할 수 있습니다**
🙇 **gitignore 대상에서 빠진 로컬 application.yml이 덮어씌워져 PR에 올라올 수 있으니 주의해주세요**  
💦 핫픽스 머지 전이라 테스트 하나가 실패하고 있습니다   
🏎 마지막에 `approve`하는 분이 머지해주셔도 됩니다~  
<br>
- Close #206 
<br>
=> chore: 테스트용 yml 서브모듈 적용

backend/src/main/java/com/pickpick/slackevent/ui/SlackEventController.java, backend/src/main/resources/appenders/async-console-appender.xml, backend/src/main/resources/appenders/async-file-appender-info.xml, backend/src/main/resources/logback-spring.xml
Slack Event 요청값 로깅
<br><br>
- logback-spring.xml 파일 추가
- async-file-appender-info.xml 파일 추가
- async-console-appender.xml 파일 추가
- SlackEventController 에 `log.info("Slack Event: {}", requestBody)` 추가
<br><br>
https://tecoble.techcourse.co.kr/post/2021-08-07-logback-tutorial/
<br><br>
- Close #212
<br><br>
=> feat: Slack Event 요청값 로깅

backend/Jenkinsfile
젠킨스 빌드 시 테스트 미실행하도록 스크립트 추가
<br>
젠킨스 빌드 시 테스트 미실행하도록 스크립트 추가
<br>
=> hotfix: 젠킨스 빌드 시 테스트 미실행

frontend/package-lock.json, frontend/package.json, frontend/src/@atoms/index.ts, frontend/src/App.tsx, frontend/src/components/Snackbar/index.tsx, frontend/src/components/Snackbar/style.ts, frontend/src/hooks/useSnackbar.ts, frontend/src/index.tsx, frontend/src/pages/Home/index.tsx
스낵바 컴포넌트 구현 및 적용
<br><br>
- Recoil 설치 및 적용
- Snackbar 컴포넌트, useSnackbar 커스텀 훅 구현 
- Close #163 
<br><br>
=> feat: 스낵바 컴포넌트 구현

frontend/src/pages/NotFound/index.tsx, frontend/src/pages/NotFound/style.ts
NotFound component style 추가
<br><br>
- 현재 UI에 맞게 NotFound component style 추가
<br><br>
- Close #228 
<br><br>
=> style: NotFound component style 추가

frontend/src/api/channels.ts, frontend/src/components/@layouts/LayoutContainer/index.tsx, frontend/src/components/@layouts/LayoutContainer/style.ts
이전 작업 하다가 Styled Component 하나를 모르고 삭제해서..로컬에서 에러뜬 채로 피알을 보냈어서, 다시 복구하여 hotfix 처리 합니다.
- 그 외에도, getAuthorization 함수 누락된 것 추가했습니다.
<br><br>
=> hotfix: 삭제된 Styled Component 복구

.github/ISSUE_TEMPLATE/feature.md, backend/src/docs/asciidoc/api.adoc
issue template 및 Rest Docs 문서 수정
<br><br>
- Issue Template 에서 기본 라벨(`ALL`) 제거
- Rest Docs 에 snippets 수정
<br><br>
- Issue Template을 수정한거라 프론트도 같이 리뷰어 올립니당,,,
<br><br>
- Close #227 
<br><br>
=> docs: issue template 및 Rest Docs 문서 수정

frontend/src/components/@shared/WrapperButton/index.tsx, frontend/src/components/@shared/WrapperButton/style.ts, frontend/src/components/Calendar/index.stories.js, frontend/src/components/Calendar/index.tsx, frontend/src/components/Calendar/style.ts, frontend/src/hooks/useCalendar.ts
달력 컴포넌트 개발
<br><br>
- Calendar component 개발 및 스토리북 작성
- useCalendar custom hook 분리
- WrapperButton component props 추가(isFuture)
<br><br>
<br><br>
- Close #164 
<br><br>
=> feat: 달력 컴포넌트 개발

frontend/src/@utils/index.ts, frontend/src/components/@layouts/Navigation/index.tsx, frontend/src/components/Calendar/index.tsx, frontend/src/components/Calendar/style.ts, frontend/src/components/DropdownMenu/index.tsx, frontend/src/hooks/usePortal.ts
Calendar 컴포넌트 적용
<br><br>
- usePortal custom hook 개발
- ISOConverter util 함수로 분리
- 기존 로직 usePortal custom hook으로 변경
- 기존로직에 Calendar component 적용
<br><br>
<br><br>
- Close #250 
<br><br>
=> feat: Calendar 컴포넌트 적용

frontend/src/api/bookmarks.ts
북마크 API 명세 수정 반영
북마크 조회 , 북마크 삭제 API 명세 변경을 반영하였습니다.
- Close #263 
<br><br>
=> feat: 북마크 API 명세 수정 반영

backend/src/main/java/com/pickpick/exception/BookmarkCannotDeleteException.java, backend/src/main/java/com/pickpick/exception/BookmarkDeleteFailureException.java, backend/src/main/java/com/pickpick/message/application/BookmarkService.java, backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java, backend/src/main/java/com/pickpick/message/ui/BookmarkController.java, backend/src/test/java/com/pickpick/acceptance/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
북마크 삭제 기능 구현  
<br>
북마크 삭제 기능을 추가했습니다  
<br>  
- Close #248 
<br><br>
=> feat: 북마크 삭제 기능 구현

frontend/src/@constants/index.ts, frontend/src/Routes.tsx, frontend/src/api/auth.ts, frontend/src/components/@layouts/Header/index.tsx, frontend/src/hooks/useGetSearchParam.ts, frontend/src/mocks/handlers/auth.ts, frontend/src/pages/Certification/index.tsx, frontend/src/pages/index.tsx
슬랙 OAuth 기능을 구현했는데, 리다이렉트가 정상동작하는지 확인하기 위해서 PR 올리고 바로 머지합니다. 추후에 해당 기능에 대한 추가 PR이 올라올 수 있습니다.
- 슬랙 로그인 이후 리다이렉트 될 Certification 페이지 추가
<br><br>
- Close #266 
<br><br>
=> feat: 슬랙 OAuth 기능 구현

frontend/src/api/auth.ts, frontend/src/api/bookmarks.ts, frontend/src/api/channels.ts, frontend/src/api/index.ts, frontend/src/api/messages.ts, frontend/src/components/@layouts/Navigation/index.tsx
axios 요청에서 header 누락되는 문제 해결 
순서 잘못 지정해줘서 axios 요청에서 header 가 누락되었었습니다. 해당 문제 해결했습니다.
<br><br>
- Close #이슈번호
<br><br>
=> hotifx: axios 요청에서 header 누락되는 문제 해결 

frontend/package.json, frontend/src/api/auth.ts, frontend/src/api/bookmarks.ts, frontend/src/api/channels.ts, frontend/src/api/index.ts, frontend/src/api/messages.ts
axios 인스턴스를 privateFetcher 와 publicFetcher 로 두개로 분리하여 요청 구부 
privateFetcher : headers 에 토큰 들어감
publicFetcher : headers 에 토큰 들어가지 않음
<br><br>
=> hotfix: axios 인스턴스 수정하여 요청 headers 필요시 구분 

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/auth/ui/AuthController.java, backend/src/main/java/com/pickpick/config/AuthenticationPrincipalConfig.java, backend/src/test/java/com/pickpick/acceptance/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
토큰 검증 api 구현
<br>
인가가 필요한 api 호출 전 호출할 토큰 검증용 api를 추가 구현했습니다 
<br>
=> feat: 토큰 검증 api 구현

frontend/src/@types/shared.ts, frontend/src/api/auth.ts, frontend/src/pages/Certification/index.tsx
슬랙 로그인 후 토큰 쿠키에 저장하는 로직 추가
<br><br>
- Close #이슈번호
<br><br>
=> hotfix: 슬랙 로그인 후 토큰 쿠키에 저장하는 로직 추가

frontend/src/api/bookmarks.ts, frontend/src/components/PrivateRouter/index.tsx, frontend/src/components/PublicRouter/index.tsx
사용자 인증 api 요청 retry 횟수 수정 및 디폴트 Query param value 수정
<br><br>
=> hotfix: 사용자 인증 api 요청 retry 횟수 수정 및 디폴트 Query param value 수정

frontend/src/api/auth.ts, frontend/src/components/PrivateRouter/index.tsx, frontend/src/components/PublicRouter/index.tsx, frontend/src/hooks/useAuthentication.ts, frontend/src/pages/Certification/index.tsx
슬랙 로그인 후 쿼리 무효화 추가하여 인증 상태 재검증 하도록 수정
<br><br>
=> hotfix: 슬랙 로그인 후 쿼리 무효화 추가하여 인증 상태 재검증 하도록 수정

backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java, backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
파일 공유 메시지 저장 구현
<br><br>
- SlackEvent에 MESSAGE_FILE_SHARE 이벤트 추가
- MessageFileShareService 및 테스트 추가
<br><br>
- 텍스트 없이 파일을 공유할 때에라도, 빈 문자열로 저장하도록 구현했습니다
- 빈 문자열로 파일만 공유한 뒤에 추후 편집을 통해 메시지를 추가할 수 있기 때문입니다
- 이 경우, message_changed 이벤트에서 대응하려면 빈 텍스트라도 저장해둬야 해서 위와 같이 구현했습니다
- 다만, 메시지 조회 시점에 빈 문자열을 필터링해줘야 하는데, 이는 별도 태스크로 진행하겠습니다.
<br><br>
- Close #224 
<br><br>
=> feat: 파일 공유 메시지 저장 구현

frontend/src/Routes.tsx, frontend/src/api/auth.ts, frontend/src/api/bookmarks.ts, frontend/src/api/channels.ts, frontend/src/api/index.ts, frontend/src/api/messages.ts, frontend/src/api/utils.ts, frontend/src/hooks/useAuthentication.ts, frontend/src/pages/Home/index.tsx
로그인/로그아웃 버그 해결
- 로그인 이후 navigate 안되는 문제 해결 
- 로그아웃 이후 인증 제대로 되지 않는 문제 해결
<br><br>
=> hotfix : 로그인/로그아웃 버그

frontend/src/pages/Feed/index.tsx
채널 선택시 리렌더링 되지 않는 문제 해결
<br><br>
- 채널 선택시 리렌더링 되지 않는 문제 해결
<br><br>
=> hotfix: 채널 선택시 리렌더링 되지 않는 문제 해결

frontend/src/components/@layouts/Navigation/index.tsx, frontend/src/components/Drawer/index.tsx
선택된 채널 다시 선택했을 경우 drawer 닫히지 않는 버그 수정
<br><br>
선택된 채널 다시 선택했을 경우 drawer 닫히지 않는 버그 수정
<br><br>
=> hotfix: 선택된 채널 다시 선택했을 경우 drawer 닫히지 않는 버그 수정

backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
모든 멤버가 본인으로 뜨는 에러 해결
<br><br>
<br><br>
=> fix: 모든 멤버가 본인으로 뜨는 에러 해결

frontend/src/api/messages.ts
=> hotfix: 잘못된 queryParam 수정

backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java, backend/src/main/java/com/pickpick/channel/domain/ChannelSubscription.java, backend/src/main/java/com/pickpick/exception/SubscriptionInvalidOrderException.java, backend/src/main/java/com/pickpick/exception/SubscriptionNotExistException.java, backend/src/main/java/com/pickpick/exception/SubscriptionOrderDuplicateException.java, backend/src/main/java/com/pickpick/exception/SubscriptionOrderMinException.java, backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
채널 구독 예외 케이스 PR의 리뷰가 반영되기 전에 머지되어서, 새 PR에 리뷰 반영해서 올립니다.
<br><br>
- 코드 컨벤션들(final, 띄어쓰기, 줄넘김) 반영
- Exception 및 함수 이름 변경
- !allMatch() - containsAll로 변경 
<br><br>
- comment로 의견 여쭙고 싶은 부분들 남겼습니다 확인 부탁드려요 :) 
<br><br>
- #275 
<br><br>
=> refactor: 채널 구독 예외 케이스 리뷰 반영

frontend/src/components/EmptyStatus/index.stories.js, frontend/src/components/EmptyStatus/index.tsx, frontend/src/hooks/usePushPreviousPage.ts, frontend/src/pages/Bookmark/index.tsx, frontend/src/pages/Feed/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
데이터 없다는 것을 전달할 수 있는 컴포넌트 개발
<br><br>
```tsx
import { useNavigate } from "react-router-dom";
type ReturnType = () => void;
function usePushPreviousPage(): ReturnType {
const navigate = useNavigate();
const pushPreviousPage = () => {
navigate(-1);
};
return pushPreviousPage;
}
export default usePushPreviousPage;
```
뒤로가기 기능이 나중에 재사용될수 있겠다고 판단해서 훅으로 분리해보았어용 
- DataFetching 상태가, isSuccess 이고 ParsedData 의 length 가 0 일 때 
- isSuccess 를 붙여주지 않으면, isLoading 일 때 화면에 아주 잠깐, EmptyStatus 컴포넌트가 보여서 , isSuccess flag 를 사용했습니다. 
<br><br>
- Close #337 
<br><br>
=> feat: 데이터 없다는 것을 전달할 수 있는 컴포넌트 개발

frontend/src/components/@layouts/Navigation/style.ts, frontend/src/components/@shared/Dimmer/style.ts, frontend/src/components/DateDropdown/index.tsx, frontend/src/components/Drawer/style.ts, frontend/src/components/Dropdown/index.tsx, frontend/src/components/SearchForm/index.tsx, frontend/src/components/SearchForm/style.ts, frontend/src/components/SearchOptions/style.ts, frontend/src/hooks/useDropdown.ts, frontend/src/pages/Feed/style.ts
Dropdown 공용 컴포넌트 작성 및 리팩터링
<br><br>
- useDropdown hook 개발
- Dropdown component 개발
- DateDropdown component에  Dropdown component 적용
- SearchForm component에  Dropdown component 적용
- SearchForm component에  Dropdown component 적용
- Dropdown component props 수정
- Navigation, Dimmer, Drawer z-index 수정
- DateDropdown - position relative
- Dimmer - position fixed  z-index: 1;
- Navigation - position fixed & z-index 999
- Drawer - position fixed z-index: 2
- SearchForm - position: fixed z-index:1
-  SearchForm component position fixed로 변경
<br><br>
- Close #375 
<br><br>
=> refactor: Dropdown 공용 컴포넌트 작성 및 리팩터링

frontend/src/App.tsx
react-query-devtools 설정
<br><br>
귀엽쥬?! 
<br><br>
- Close #374 
<br><br>
=> feat: react-query-devtools 설정

frontend/src/components/@layouts/Navigation/style.ts, frontend/src/components/Calendar/style.ts, frontend/src/components/DateDropdownMenu/style.ts, frontend/src/hooks/useSelectChannels.ts, frontend/src/pages/Certification/index.tsx
z-index 수정 및 검색 채널 선택 옵션 버그 수정
<br><br>
- Close #381 
<br><br>
=> fix: z-index 수정 및 검색 채널 선택 옵션 버그 수정

backend/src/main/java/com/pickpick/PickpickApplication.java, backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/exception/SlackApiCallException.java, backend/src/main/java/com/pickpick/exception/SlackClientException.java, backend/src/main/java/com/pickpick/exception/message/SlackSendMessageFailureException.java, backend/src/main/java/com/pickpick/message/application/ReminderSender.java, backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
리마인드 메시지 전송 기능 구현
<br><br>
- 10분마다 리마인드 메시지 전송
- 시간이 지난 리마인더 DB에서 삭제
<br><br>
- Close #388 
<br><br>
=> feat: 리마인드 메시지 전송 기능 구현

frontend/src/api/messages.ts
getMessages API 요청시 query params 리팩터링
<br><br>
- Close #373 
<br><br>
=> refactor: getMessages API 요청시 query params 리팩터링

frontend/src/components/MessageCard/index.tsx
MessageCard component Props 설정
=> hotfix: MessageCard component Props 설정

backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/pickpick/exception/message/ReminderNotFoundException.java, backend/src/main/java/com/pickpick/message/application/ReminderService.java, backend/src/main/java/com/pickpick/message/ui/ReminderController.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java, backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
리마인더를 단건 조회하는 기능 구현
<br><br>
- 리마인더를 단건 조회할 수 있는 api를 개발
- controllertest 추가하여 rest docs 볼 수 있음
<br><br>
- 나머지 테스트는 후에 따로 이슈로 추가
<br><br>
- Close #428 
<br><br>
=> feat: 리마인더를 단건 조회하는 기능 구현

backend/src/docs/asciidoc/index.adoc, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java, backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
리마인더 단건 조회 관련 service 및 acceptance test 추가
<br><br>
- 리마인더 단건 조회 관련 서비스 테스트 추가
- 리마인더 단건 조회 관련 인수 테스트 추가
<br><br>
- #430 PR의 테스트코드가 부족한 부분을 보완했습니다.
<br><br>
=> test: 리마인더 단건 조회 관련 service 및 acceptance test 추가

frontend/src/hooks/useSelectChannels.ts
검색 채널 옵션 선택 버그 해결
- 현재 방문중인 채널이 체크되지 않는 에러 해결
- 전체 선택이 되지 않는 에러 해결
<br><br>
<br><br>
- Close #454
<br><br>
=> fix: 검색 채널 옵션 선택 버그 해결

backend/src/main/java/com/pickpick/auth/support/JwtTokenProvider.java, backend/src/main/java/com/pickpick/channel/domain/ChannelSubscription.java, backend/src/main/java/com/pickpick/exception/auth/ExpiredTokenException.java, backend/src/main/java/com/pickpick/exception/auth/InvalidTokenException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionInvalidOrderException.java
예외 메시지에 데이터도 포함되도록 수정
<br><br>
편리한 QA를 위해 빠른 머지가 되면 좋을 것 같아요~
<br><br>
=> feat: 예외 메시지에 데이터도 포함되도록 수정

frontend/src/components/@layouts/Navigation/index.tsx, frontend/src/components/SearchOptions/index.tsx, frontend/src/hooks/useApiError.ts, frontend/src/hooks/useAuthentication.ts, frontend/src/hooks/useRecentFeedPath.ts, frontend/src/pages/Feed/index.tsx, frontend/src/pages/SearchResult/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
QA 1차 반영
<br><br>
1.  검색 결과 페이지에서 재검색 결과 렌더링되지 않는 이슈 해결
2. main 채널의 특정 날짜 피드 페이지의 경우 검색 채널 옵션에서 채널 선택이 안되어있는 문제 해결
3. '로그인이 필요한 서비스입니다' 스낵바 메시지 제거
4. '검색할' -> '검색 할'로 수정 
5. 네비게이션 바에서 홈버튼 눌렀을 때 , 가장 최근에 방문한 Feed 페이지 렌더링 되도록 수정
=> refactor: QA 1차 반영 

frontend/src/components/@layouts/Footer/index.tsx, frontend/src/components/Dropdown/index.tsx, frontend/src/components/SearchForm/index.tsx, frontend/src/components/Snackbar/style.ts, frontend/src/hooks/useOuterClick.ts, frontend/src/pages/Bookmark/index.tsx, frontend/src/pages/Feed/index.tsx, frontend/src/pages/Reminder/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
QA 2차 반영
<br><br>
- Feed, Reminder, Bookmark, SpecificDateFeed 접근시 스크롤 상단으로 이동하도록 변경
- useOuterClick custom hook ref type 재설정 (any type 제거)
- Snackbar 메시지 dimmer 밑에 깔리는 문제 수정 z-index: 3;으로 수정
- github icon 클릭시 github page로 이동 및 footer component 필요없는 태그 제거
<br><br>
=> refactor: QA 2차 반영

frontend/src/@styles/GlobalStyle.ts, frontend/src/components/@layouts/LayoutContainer/index.tsx, frontend/src/pages/AddChannel/index.tsx, frontend/src/pages/AddChannel/style.ts
QA5차 반영
<br><br>
채널선택 페이지에서 네비게이션 바 제거 및 디자인 수정
<br><br>
=> refactor: QA5차 반영

.gitmodules, backend/src/test/resources/application.yml
운영용 slack app 추가 및 yml 설정 정리
<br><br>
1. prod용 app 추가
2. BE yml 파일 수정
> 서브모듈의 아래 변경 사항을 프로젝트에 적용
- 불필요한 yml 파일 분리 제거
- test용 yml 파일 제거
<br><br>
- Close #488 
<br><br>
=> chore: 운영용 slack app 추가 및 yml 설정 정리

frontend/src/components/Calendar/index.tsx, frontend/src/components/Calendar/style.ts, frontend/src/hooks/useCalendar.ts
달력 컴포넌트에서 미래 날짜 혹은 날짜가 비어있는 곳을 클릭할 경우 데이터 요청을 하는 버그 수정
<br><br>
- 71b13bf fix: isBlank, isFuture인 day 클릭시 link 이동되는 버그 해결
- 26307a7 refactor: isBlank, isFuture 인 경우 클릭 이벤트 발생하지 않도록 css 수정
- 27c6746 refactor: 매번 생성되는 date 객체 최소한으로 생성될 수 있도록 변경
<br><br>
버그 수정하면서 new Date 객체를 함수 호출시 마다 생성하는 부분이 존재해 해당하는 부분도 같이 제거해줬습니다.
같이 확인해주세요~! 
- Close #517 
<br><br>
=> fix: 달력 컴포넌트 미래 날짜 및 빈 공간 클릭시 데이터 요청되는 버그 수정

frontend/src/components/@svgIcons/SearchIcon.tsx, frontend/src/components/SearchForm/index.tsx, frontend/src/components/SearchOptions/index.tsx, frontend/src/hooks/useSelectChannels.ts
SearchForm component 리렌더링 최소화 로직 추가
- Close #522 
<br><br>
=> refactor: SearchForm component 리렌더링 최소화 로직 추가

backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java, backend/src/main/java/com/pickpick/channel/ui/ChannelSubscriptionController.java, backend/src/main/java/com/pickpick/message/ui/ReminderController.java, backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
Service Layer에서 완성된 DTO 반환
<br><br>
1. Service Layer에서 완성된 DTO 반환
2. 메서드 순서 CRUD로 변경
예상 외로 DTO로 반환할게 별로 없네요!
자잘하게 수정했습니다 😄
<br><br>
- Close #489 
<br><br>
=> feat: Service Layer에서 완성된 DTO 반환

frontend/src/pages/UnexpectedError/index.tsx
=> hotfix: remove import 문 제거

backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java, backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelDeletedEventDto.java, backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelDeletedRequest.java, backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelEventDto.java, backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRenameRequest.java, backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java, backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java
channel event의 request 형식 변경
<br><br>
모든 request값은 event 안에 존재
<br><br>
=> hotfix: channel event의 request 형식 변경

frontend/src/components/@layouts/LayoutContainer/style.ts
=> hotfix: UI 버그 수정 

backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java
누락된 파일 추가 
<br>
`ChannelDeletedService`가 현재 예전 버전으로 들어가있습니다
그래서 남아있던 최신 백업 파일로 교체했습니다
<br>
변경이 있던 파일 목록인데, 다른 파일은 이상 없음을 확인했어요  
<br>
=> hotfix: 누락된 파일 추가

backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java
백엔드 쪽 누락된 코드 파일 추가  
<br>
깃 충돌을 해결하던 중, 백엔드 특정 파일이 누락되었습니다 
이 파일을 백업 브랜치와 비교해 정상적으로 추가했습니다  
<br>
=> fix: 누락된 파일 추가 (#543)

backend/src/main/java/com/pickpick/message/application/ReminderSender.java
리마인드 메시지 뷰 개선
<br><br>
- *리마인드 메시지가 도착했습니다* 볼드처리
- 메시지 도착 멘트 위 아래로 구분선 추가
- `>` 인용 부호 삭제
<br><br>
<br><br>
- Close #552 
<br><br>
=> refactor: 리마인드 메시지 뷰 개선

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/channel/application/ChannelCreateService.java, backend/src/main/java/com/pickpick/exception/SlackApiCallException.java, backend/src/main/java/com/pickpick/member/application/MemberInitializer.java, backend/src/main/java/com/pickpick/message/application/ReminderSender.java, backend/src/main/java/com/pickpick/support/SlackClient.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java, backend/src/test/java/com/pickpick/channel/application/ChannelCreateServiceTest.java, backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java, backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java, backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
외부 라이브러리의 로직 추상화 
<br><br>
- MethodClient를 사용하는 로직들을 모아 추상화하여 SlackClient 생성
- MethodClient 대신 SlackClient 사용
- MethodClient를 모킹한 테스트 클래스에서 ok 값 세팅
<br><br>
다른 PR들이 머지되면 충돌이 날 예정이라 수정 후 ✨`셀프 머지`✨ 할게요
SlackConfig를 제거하고 싶지만 테스트에서 모킹한 데이터들 때문에 당장은 힘들거라고 판단했습니다.
이후에 모든 테스트에서 모킹을 제거하는 태스크에서 제거해야할 것 같아요~
<br><br>
- Close #566 
<br><br>
=> refactor: 외부 라이브러리의 로직 추상화 

frontend/src/components/@layouts/Navigation/index.tsx, frontend/src/components/@shared/Modal/index.tsx, frontend/src/pages/Feed/index.tsx, frontend/src/pages/Reminder/index.tsx, frontend/src/pages/SearchResult/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
Modal component 생성 및 중복되는 컴포넌트 제거
<br><br>
- Close #574 
<br><br>
=> refactor: Modal component 생성 및 중복되는 컴포넌트 제거

backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
의도/내용물과 달리 잘못 표기된  DisplayName과 메서드명 정정
<br>
고친 코드 길이보다 PR 제목이 더 긴 사소한 수정입니다 😂 
<br>
=> fix: 잘못 표기된 DisplayName과 메서드명 정정

backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/RestHandler.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelRestHandler.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkRestHandler.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/MessageRestHandler.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderRestHandler.java, backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRequestFactory.java, backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRestHandler.java
메시지 관련 인수 테스트 개선
<br><br>
메시지, 북마크, 리마인더 인수 테스트 개선
<br><br>
인수 테스트 리팩터링 마지막 PR 입니다 😄
<br><br>
- Close #565 
<br><br>
=> test: 메시지 인수 테스트 개선

frontend/src/@styles/shared.ts, frontend/src/api/index.ts, frontend/src/components/Calendar/index.tsx, frontend/src/components/Calendar/style.ts, frontend/src/components/DateDropdown/DateDropdownMenu/index.tsx, frontend/src/components/DateDropdown/DateDropdownOption/index.tsx, frontend/src/components/DateDropdown/index.tsx, frontend/src/components/DateDropdown/style.ts, frontend/src/components/EmptyStatus/index.tsx, frontend/src/components/EmptyStatus/style.ts, frontend/src/components/MessageCard/MessageCardSkeleton/index.tsx, frontend/src/components/MessageCard/MessageIconButtons/BookmarkButton/index.tsx, frontend/src/components/MessageCard/MessageIconButtons/ReminderButton/index.tsx, frontend/src/components/MessageCard/index.tsx, frontend/src/components/MessageCard/style.ts, frontend/src/pages/AddChannel/index.tsx, frontend/src/pages/AddChannel/style.ts, frontend/src/pages/Bookmark/index.tsx, frontend/src/pages/Feed/index.tsx, frontend/src/pages/Feed/style.ts, frontend/src/pages/Home/index.tsx, frontend/src/pages/Home/style.ts, frontend/src/pages/Reminder/index.tsx, frontend/src/pages/SearchResult/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
=> refactor: 웹 접근성 적용 (1차)

backend/src/main/java/com/pickpick/message/application/ReminderSender.java, backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java, backend/src/test/java/com/pickpick/message/application/ReminderSenderTest.java
리마인더 로직 개선
<br><br>
DB 작업 수행중에 오류가 발생하는 경우 작업이 도중에 멈출 수 있는 위험 제거
<br><br>
=> refactor: 리마인더 로직 개선

backend/src/main/java/com/pickpick/message/application/BookmarkService.java, backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/application/ReminderService.java, backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java, backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
멘션에 @ 기호 추가
<br><br>
멘션 같지가 않아서 @ 기호 추가했습니다!
<br><br>
=> feat: 멘션에 @ 기호 추가

README.md
리드미 기술스택 추가 및 스토리북 주소 변경 
- 저번에 만들어놨던 기술스택 이미지 추가했어요!
- 스토리북 주소도 변경되어서 수정해놨어요!
혹시 더 추가할 사항이 있으면 말하거나 직접 해주셔도 무관합니다!
<br><br>
=> docs: 리드미 기술스택 추가 및 스토리북 주소 변경 

README.md
=> docs: 스토리북 주소 수정

frontend/src/@constants/message.ts, frontend/src/hooks/useApiError.ts, frontend/src/pages/RegisterSlackWorkspace/index.tsx
- 중복된 워크스페이스일 경우 home으로 redirect
- 워크스페이스 등록 성공시 스넥바 메시지 추가
=> hotfix: workspace 등록 로직 수정

frontend/public/index.html
검색엔진 최적화를 위한 meta tag 설정
<br><br>
meta tag로 author, description, keywords, robots를 설정해줬습니다.
author는 저자 설정
description은 사이트 부연 설정
keywords는 검색엔진에 걸릴 수 있도록 설정하는 키워드 입니다. (추가로 설정하고 싶은게 있다면 말씀해주시면 추가할게요!)
robots의 index, nofollow는 페이지를 웹크롤러가 읽을 수 읽게 설정(index)하고, nofollow는 웹에 존재하는 외부 링크는 크롤러가 읽지 못하도록 설정하는 옵션입니다.
noindex, follow도 존재하는데 위 설명의 반대로 생각해주시면 될 것 같아요!
<br><br>
기존에 검색엔진 최적화는 80점이였는데 meta tag 몇게 추가 했더니 100점으로 올랐어요! 와우!
<br><br>
- Close #681 
<br><br>
=> feat: 검색엔진 최적화를 위한 meta tag 설정

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/auth/application/dto/OAuthAccessInfoDto.java, backend/src/main/java/com/pickpick/auth/application/dto/WorkspaceInfoDto.java, backend/src/main/java/com/pickpick/auth/ui/AuthController.java, backend/src/main/java/com/pickpick/support/ExternalClient.java, backend/src/main/java/com/pickpick/support/SlackClient.java, backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java, backend/src/main/java/com/pickpick/workspace/ui/WorkspaceController.java, backend/src/test/java/com/pickpick/acceptance/AcceptanceTestBase.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthRestHandler.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceRestHandler.java, backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java, backend/src/test/java/com/pickpick/support/DocsControllerTestBase.java, backend/src/test/java/com/pickpick/support/FakeClient.java, backend/src/test/java/com/pickpick/workspace/application/WorkspaceServiceTest.java
워크스페이스 등록 후 바로 로그인
<br><br>
워크스페이스 등록 후 바로 로그인이 가능하도록 구현했습니다.
<br><br>
- Close #675 
<br><br>
=> feat: 워크스페이스 등록 후 바로 로그인

frontend/src/api/auth.ts, frontend/src/hooks/@query/useGetRegisterSlackWorkspace.ts, frontend/src/pages/RegisterSlackWorkspace/index.tsx
슬랙 워크스페이스 등록 플로우 수정
<br><br>
백엔드 코드도 수정하고 반영되면 정상적으로 동작할거에요~! 😊
<br><br>
- Close #673 
<br><br>
=> refactor: 슬랙 워크스페이스 등록 플로우 수정

frontend/src/@constants/message.ts
스낵바 메시지 어투 수정
- 스낵바 메시지의 어투를 🥕 마켓 어투로 수정했습니다! 😄 
- placeholder 는 이미 해당 어투로 되어있어서 수정 할 사항이 없었습니다.
- 누락된 메시지 상수화를 했습니다.
- Close #674 
<br><br>
=> refactor: 스낵바 메시지 어투 수정

frontend/package.json
- dev, prod build시 타입 체크 실패할 경우 빌드 되지 못하도록 추가 설정
<br><br>
- dev, prod build시 타입 체크 실패할 경우 빌드 되지 못하도록 추가 설정
<br><br>
웹팩 최적화 진행하고 scripts 태그에 tsc 추가하는 것을 빠뜨려 추가해줬어요!
build시 tsc로 타입체크하고 타입이 실패할 경우 빌드가 되지 못하도록 설정했습니다.
<br><br>
- #695 추가 작업이에용!
<br><br>
=> refactor: package.json scripts 변경
