.github/reviewers.yml, .github/workflows/auto_request_review.yml
- 리뷰어 자동 할당 github action 추가 
- auto_request_review.yml 작성
- reviewers.yml 작성
- Closes #65
=> docs: 리뷰어 자동 할당 github action 추가 

backend/build.gradle, backend/src/main/java/com/pickpick/controller/MessageController.java, backend/src/main/java/com/pickpick/controller/dto/MessageDto.java, backend/src/main/java/com/pickpick/controller/dto/SlackMessageRequest.java, backend/src/main/java/com/pickpick/controller/dto/SlackMessageResponse.java, backend/src/main/java/com/pickpick/controller/dto/SlackMessageResponses.java, backend/src/main/java/com/pickpick/entity/Channel.java, backend/src/main/java/com/pickpick/entity/Message.java, backend/src/main/java/com/pickpick/exception/MessageNotFoundException.java, backend/src/main/java/com/pickpick/exception/WrongMessageRequestException.java, backend/src/main/java/com/pickpick/repository/MessageRepository.java, backend/src/main/java/com/pickpick/service/MessageCreatedService.java, backend/src/main/java/com/pickpick/service/MessageService.java, backend/src/test/java/com/pickpick/acceptance/EventAcceptanceTest.java, backend/src/test/java/com/pickpick/service/MessageServiceTest.java, backend/src/test/resources/message.sql
- 저장된 Slack 메시지들을 조회할 수 있는 API 구현
<br><br>
- QueryDSL 도입
- 채널 진입 시 -> 채널 ID로 최근 20개 메시지 조회
`/api/messages?channelId={channelId}`
- 특정 날짜로 이동 -> 채널 ID + 날짜로 과거 20개 조회 (날짜는 ISO 포맷으로)
`/api/messages?channelId={channelId}&date={date}`
- 쿼리 스트링으로 과거 or 미래 방향 설정 가능
`/api/messages?channelId={channelId}&date={date}&needPastMessage={true/false}`
- 쿼리 스트링으로 조회 갯수 설정 가능
`/api/messages?channelId={channelId}&date={date}&messageCount=10`
- 특정 메시지 이전 또는 이후 검색 -> 채널 ID + 메시지 ID 로 과거 20개 
`/api/messages?channelId={channelId}&messageId={messageId}`
- 쿼리 스트링으로 과거 or 미래 방향 설정 가능
`/api/messages?channelId={channelId}&messageId={messageId}&needPastMessage={true/false}`
- 쿼리 스트링으로 조회 갯수 설정 가능
`/api/messages?channelId={channelId}&messageId={messageId}&messageCount=10`
<br><br>
- 연로그와 PR 올리는 부분은 합의하지 않았는데.. 아래와 같은 …
=> feat: 메시지 조회 API 구현

backend/src/main/java/com/pickpick/controller/ChannelSubscriptionController.java, backend/src/main/java/com/pickpick/controller/dto/ChannelOrderRequest.java, backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionRequest.java, backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionResponse.java, backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionResponses.java, backend/src/main/java/com/pickpick/entity/ChannelSubscription.java, backend/src/main/java/com/pickpick/exception/ChannelNotFoundException.java, backend/src/main/java/com/pickpick/exception/MemberNotFoundException.java, backend/src/main/java/com/pickpick/exception/SlackEventNotFoundException.java, backend/src/main/java/com/pickpick/repository/ChannelRepository.java, backend/src/main/java/com/pickpick/repository/ChannelSubscriptionRepository.java, backend/src/main/java/com/pickpick/repository/MemberRepository.java, backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java
채널 구독 추가, 수정, 삭제 api 개발 
<br>
- 구독한 채널 목록 조회 API (GET)
`GET /api/channel-subscription`  
- 채널 구독 추가 API (POST)
`POST /api/channel-subscription`  
- 드래그앤 드롭으로 순서를 바꿨을 경우 수정 API (PUT)
`PUT /api/channel-subscription`  
- 채널 구독 제거 API (DELETE)
`DELETE api/channel-subscription/{channelId}`
위 4가지 경우에 대한 기능과 API 를 구현완료 했습니다.
<br>
1. `read-channels`에서 파생된 브랜치라, 우선 base를 `read-channels`로 설정하여 pr 올립니다. 일단 기능 위주로 리뷰 남겨주시면 감사하겠습니다. 🥺  
2. 현재 채널 데이터가 모킹 상태라 데이터에 의존적인 테스트가 되어 추가하지 않았습니다.
해당 `PR`에 푸시하거나, 추후 이슈를 따로 파서 데이터와 격리된 테스트를 작성하려 합니다. 😅   
<br>
- Close #87 
<br>
=> feat: 채널 구독 기능 및 api 개발 

backend/src/main/java/com/pickpick/service/MessageService.java
메시지 조회 API 오류 수정
<br><br>
channelId를 검증해야 하는 곳에서 messageId를 검증하고 있어서 500 에러가 나고 있었어요.
<br><br>
- Close #105 
<br><br>
=> fix: 메시지 조회 API 오류 수정.

backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/ChannelSubscriptionAcceptanceTest.java, backend/src/test/resources/channel.sql, backend/src/test/resources/truncate.sql
채널과 채널 구독 인수테스트 추가
- channelAcceptanceTest 추가
- channelSubscriptionAcceptanceTest 추가
acceptanceTest 에 변경사항이 있습니다.
channel.sql 문이 추가되었습니다.
truncate.sql에 delete channel_subscription을 추가했습니다.
- Close #104 
<br><br>
=> test: 채널과 채널 구독 인수테스트 추가

backend/src/main/java/com/pickpick/controller/dto/SlackMessageRequest.java, backend/src/main/java/com/pickpick/service/MessageService.java
두 가지 이슈를 대응했습니다.
- `needPastMessage=false` 일 경우 응답값이 시간 오름차순으로 응답되는 오류
- 마지막 메시지임에도 `isLast` 가 `false` 로 응답되는 오류 
<br><br>
- QueryDSL 로 데이터를 조회해오는 부분에서 getTimeCondition 오류를 수정했습니다.
- 미래 메시지를 요청한 경우 조회해온 메시지를 Java에서 내림차순으로 재정렬해 응답해주었습니다.
- isLast 로직 관련 타겟 메시지를 가져오는 로직의 오류를 수정했습니다.
<br><br>
- Close #121 
- Close #122
<br><br>
=> hotfix: 메시지 조회 API 응답 관련 오류 수정

frontend/src/components/@shared/Dimmer/style.ts, frontend/src/components/Drawer/style.ts, frontend/src/components/Dropdown/style.ts, frontend/src/components/layouts/Navigation/style.ts
-  z-index 수정
<br><br>
- Dimmer, Drawer, Dropdown z-index 제거
- Navigation z-index 수정
기존에 위와 같이 DropDown 의 z index와 Dimmer 의 z-index 의 우선순위가 충돌되는 문제 해결
<br><br>
최대한 z-index 를 사용하지 않는 것이, 추후에 쌓임맥락을 관리할 때 간편할거라 생각하여,  일단 포털 상관없이 맨 최상단에 와야 하는 Navigation 을 제외하고 z-index를 모두 제거했습니다 ! ! 
1. Position 이 absolute 혹은 relative 
2. Position 이 fixed 혹은 sticky 
```
- DropDown - position relative
- Dimmer - position fixed
- Navigation - position fixed & z-index 1 
- Drawer - posiiton fixed
```
- 포탈을 썼기 때문에 아래 div 에 추가 되어 Dropdown 의 position relative 쌓임맥락은 아래로 가게 된다.
- Dimmer , Drawer 두개는 쌓임맥락이 같지만, 순서대로 쌓여서  Drawer 가 더 먼저 오게 된다.
- Navigation 은 z-index 를 1로 두어 언제나 위에 두게 한다.
- Navigation의 쌓임 맥락 > DropDown 의 쌓임 맥락 > Dimmer 쌓임맥락 
<br><br>
- Close #114 
<br><br>
=> fix: z-index 수정

backend/src/main/java/com/pickpick/controller/ControllerAdvice.java, backend/src/main/java/com/pickpick/controller/dto/ChannelOrderRequest.java, backend/src/main/java/com/pickpick/exception/DuplicatedSubscriptionException.java, backend/src/main/java/com/pickpick/exception/SubscriptionDuplicatedException.java, backend/src/main/java/com/pickpick/exception/SubscriptionNotExistException.java, backend/src/main/java/com/pickpick/repository/ChannelSubscriptionRepository.java, backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java, backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/ChannelSubscriptionAcceptanceTest.java
구독 관련 중복 요청 시 예외처리 추가
`POST /api/channel-description`
`DELETE /api/channel-description/{channelId}`
API 호출 시 
- 이미 구독 중인 채널을 다시 구독할 경우 DB에 중복저장되던 버그에 예외처리 추가
- 구독중이지 않은 채널을 구독 취소할 경우 예외처리 추가
**1)** @slf4j 를 이용하여 간단하게 로깅 추가했습니다.
로그로 남은 에러메시지 형식은 **추후 협의하여 수정**하면 좋을 것 같습니다.
**2)** #132 이슈를 반영하여 ChannelOrderRequest에 기본 생성자 추가했습니다. 
<br><br>
- Close #107 
- Close #132 
<br><br>
=> feat: 구독 관련 중복 요청 시 예외처리 추가

frontend/src/pages/Feed/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
모바일에서 onWheel 이벤트를 touch 이벤트로 대체
<br><br>
- 상단 무한 스크롤에 touch 이벤트 추가
- messages.at(-1) -> messages[message.length -1) 로 변경
<br><br>
- Close #140 
<br><br>
=> feat: 모바일에서 onWheel 이벤트를 touch 이벤트로 대체

backend/src/main/java/com/pickpick/config/QuerydslConfig.java, backend/src/main/java/com/pickpick/service/MessageService.java, backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
- 메시지 조회 API 동적 검색 조건 생성 로직 리팩터링
<br><br>
- MessageService 클래스 내 where 절에 들어가던 내용을 리팩터링했습니다
- 기존 BooleanBuilder를 이용해 하나의 메서드에서 모든 로직 생성하던 부분을 분리해냈습니다
- BooleanExpression 으로 개별 검증 단위마다 메서드로 분리하여 이를 조합하도록 구현했습니다
- isLastExpression도 함께 리팩터링 진행했습니다
- 테스트 픽스처 하나 수정했습니다
- 시간으로 조회할 경우 전달된 시간을 포함하여 검색해야하기 때문에 픽스처를 수정했습니다
- 가령 7월 1일로 이동하면, 7월1일23시59분59초를 전달하는데, 이때 이 시간도 포함해서 검색해야 하기 때문입니다.
- JpaQueryFactory 를 어디서든 생성자 주입 받을 수 있게 설정을 추가하였습니다
<br><br>
- https://jojoldu.tistory.com/372
- https://youtu.be/zMAX7g6rO_Y?t=176
<br><br>
- Close #157 
<br><br>
=> refactor: 메시지 조회 API 동적 쿼리 생성 로직 리팩터링

backend/src/main/java/com/pickpick/message/application/MessageService.java
compileQuerydsl 수행 중, QMessage를 찾지 못해 빌드 실패
<br><br>
Message 엔티티 경로 변경으로 인한 import 이슈
MessageService 내 잘못 import 된 문장 삭제 및 현재 경로로 정상 import 수행
<br><br>
- Close #170 
<br><br>
=> fix: 패키지 구조 변경 후 QMessage import 이슈 수정

backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java, backend/src/main/java/com/pickpick/channel/ui/ChannelSubscriptionController.java, backend/src/main/java/com/pickpick/channel/ui/dto/ChannelSubscriptionRequest.java, backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java
구독 생성, 삭제 API 스펙 변경
<br><br>
**- 구독시**
POST /api/channel-subscription
{
"channelId": 1
}
**-구독 해제 시**
DELETE /api/channel-subscription?channelId={channelId}
<br><br>
- Close #181 
<br><br>
=> refactor: 구독 생성, 삭제 API 스펙 변경

frontend/src/@constants/index.ts, frontend/src/pages/AddChannel/index.tsx, frontend/src/pages/Feed/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
react-query queryKey 상수화
- React Query 에서 사용되는 Query Key 상수화 하여 관리 
- AllChannels, AllMessages, SpecificDateMessgaes 쿼리키 상수화 
추후에 쿼리키가 중복되면 문제 생길 것 같아서 상수로 관리 했습니다.
- Close #185
<br><br>
=> refactor: react-query queryKey 상수화

backend/src/main/java/com/pickpick/message/application/MessageService.java
- 메시지 조회 API 관련 추가 리팩터링 피드백 반영
<br><br>
- 메서드 네이밍, 변수명 네이밍 개선
- limit 전에 정렬 조건을 동적으로 생성하는 메서드 매개변수 개선
- SlackMessageRequest -> LocalDateTime
<br><br>
- https://github.com/woowacourse-teams/2022-pickpick/pull/158
<br><br>
- Close #169 
<br><br>
=> refactor: 메시지 조회 API 네이밍 관련 추가 리팩터링

backend/src/test/java/com/pickpick/controller/ChannelSubscriptionControllerTest.java
머지 과정에서의 import issue 및 TC 깨짐 문제해결
- chore/spring-rest-docs 브랜치를 main 브랜치와 머지하는 과정에서 class가 제대로 import 되지 않은 이슈를 해결했습니다.
- chore/spring-rest-docs 브랜치를 main 브랜치와 머지하는 과정에서 main 브랜치에는 적용된 api 수정이 chore/spring-rest-docs에는 적용되지 않아 발생한 테스트 코드 깨짐 문제를 해결했습니다.
<br><br>
=> fix: Merge 과정에서의 import issue 및 테스트 코드 깨짐 문제해결

backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
- 메시지 검색어로 조회 시 대소문자 무시하도록 개선
- 테스트 픽스처 일부 수정
<br><br>
- QMessage.message.text.contains -> QMessage.message.text.containsIgnoreCase
- SlackMessageRequest.keyword=A -> SlackMessageRequest.keyword=text A
<br><br>
Github Actions 으로 빌드 및 테스트를 테스트해보고 있었는데,
두 가지 케이스가 반복적으로 실패가 되고 있어서 확인해보니 실제로 테스트가 깨지고 있었습니다
그로 인해 이번 이슈 및 PR을 생성해 작업을 진행하였고,
해당 작업이 진행될 경우 정상 빌드됨을 확인했습니다
<br><br>
- Close #177 
<br><br>
=> refactor: 검색어로 메시지 조회시 대소문자 무시하도록 개선, 테스트 픽스처 수정

backend/src/main/java/com/pickpick/config/TimeConfig.java, backend/src/main/java/com/pickpick/config/TimeZoneConfig.java
<br><br>
- 배포 시점에 디폴트 타임존을 UTC+9 로 설정
=> fix: TimeZone UTC+9 설정

frontend/src/@constants/index.ts, frontend/src/@types/shared.ts, frontend/src/api/channels.ts, frontend/src/api/messages.ts, frontend/src/components/Drawer/index.tsx, frontend/src/components/layouts/Navigation/index.tsx, frontend/src/index.tsx, frontend/src/mocks/handlers.ts
구독 중인 채널 Drawer에 보여주는 기능
<br><br>
- 불필요한 mocking handler 제거
- SubscribedChannel, ResponseSubscribedChannels 타입 추가
- getSubscribedChannels API fetcher 추가 및 api path 상수화
<br><br>
- Close #162 
<br><br>
=> feat: 구독 중인 채널 Drawer에 보여주는 기능

.github/workflows/backend-build-test.yml
- .github/workflows/backend-build-test.yml 파일 추가
- 해당 파일 내에 어떤 이벤트 발생 시 어떤 동작을 수행할 지 설정
<br><br>
- main 브랜치 내 backend 경로 하위에 merge, push, pr생성, pr 생성 후 코드 추가 이벤트 시 적용
- 수행하는 내용은 clone, jdk 설치, 타임존 설정, gradle build, Slack 알림 으로 구성됨
- woowacourse-teams/2022-pickpick 에 Repository Secret 2개 추가
- 하나는 서브 모듈 clone을 위한 토큰, 하나는 Slack 메시지 게시를 위한 웹훅 URL 토큰
<br><br>
- [Github Action을 이용한 CI 테스트 자동화](https://github.com/woowacourse-teams/2022-pickpick/wiki/Github-Action%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-CI-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%9E%90%EB%8F%99%ED%99%94)
- @yeon-06  @JangBomi  마지막에 Approve 하는 분께서 merge 해주셔도 될 것 같습니다!
<br><br>
- Close #179 
<br><br>
=> feat: Github Actions를 이용한 Backend CI 테스트 자동화

backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java, backend/src/main/java/com/pickpick/channel/domain/Channel.java, backend/src/main/java/com/pickpick/channel/domain/ChannelRepository.java, backend/src/main/java/com/pickpick/channel/ui/ChannelSubscriptionController.java, backend/src/main/java/com/pickpick/exception/SlackBadRequestException.java, backend/src/main/java/com/pickpick/member/application/MemberInitializer.java, backend/src/main/java/com/pickpick/message/domain/MessageRepository.java, backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java, backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java, backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelRenameService.java, backend/src/main/java/com/pickpick/slackevent/application/channel/dto/SlackChannelRenameDto.java, backend/src/main/java/com/pickpick/utils/AuthorizationExtractor.java, backend/src/test/java/com/pickpick/PickpickApplicationTests.java, backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/EventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/channel/domain/ChannelTest.java, backend/src/test/java/com/pickpick/message/MessageServiceTest.java, backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java, backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java, backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java, backend/src/test/resources/channel.sql
채널명 변경 이벤트 및 채널 삭제 이벤트 적용
<br><br>
- `ChannelRenameService`
- `ChannelDeletedService`
- `SlackEvent` enum에 이벤트 케이스(`CHANNEL_RENAME`, `CHANNEL_DELETED`) 추가
<br><br>
- Close #186
<br><br>
=> feat: 채널명 변경 이벤트 및 채널 삭제 이벤트 적용

backend/src/test/java/com/pickpick/controller/ChannelControllerTest.java, backend/src/test/java/com/pickpick/controller/MessageControllerTest.java, backend/src/test/java/com/pickpick/controller/RestDocsTestSupport.java, backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
이전 테스트에서 수행한 테스트 데이터가 남아있어서 테스트가 실패하고 있었습니다.
<br><br>
ChannelDeletedServiceTest 클래스에 @Sql 애너테이션을 이용해 truncate 수행하도록 처리
<br><br>
=> hotfix: ChannelDeletedServiceTest 테스트 격리 처리

.github/workflows/backend-build-test.yml, backend/src/main/java/com/pickpick/utils/TimeUtils.java
- 메시지 조회 테스트가 실패하는 원인이 타임존 설정으로 예상하여 작업을 진행하였습니다
<br><br>
- TimeUtils 내 toLocalDateTime 메서드에서 변환 시점에 systemDefault 존으로 변환하고 있던 것을 수정했습니다
- 현재는 systemDefault 에서 Zone.of("Asia/Seoul") 으로 변경되었습니다.
- 백엔드 CI 테스트 자동화 스크립트에서 TimeZone 설정을 step을 추가했습니다.
<br><br>
=> hotfix: TimeUtils 변환 로직 수정, 백엔드 CI 테스트 스크립트 타임존 설정 추가

backend/Jenkinsfile
젠킨스 빌드 명령어에 --info 옵션 추가
<br> 
젠킨스 빌드 명령어에 디버깅을 위한 --info 옵션 추가
<br>
=> hotfix: 빌드 명령어에 --info 옵션 추가

backend/Jenkinsfile
젠킨스 빌드 시 테스트 실행하도록 스크립트 변경
<br>
젠킨스 빌드 시 테스트 실행하도록 스크립트에서 `-x test` 옵션 제거  
<br>
=> hoxfix: 젠킨스 빌드 시 테스트 실행하도록 스크립트 변경

backend/src/main/java/com/pickpick/config/SlackConfig.java, backend/src/main/java/com/pickpick/member/application/MemberInitializer.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
- MemberInitailizer를 프로덕션에서만 활성화  
- MethodsClient 빈을 MemberInitailizer에 주입  
<br>
- MemberInitailizer를 프로덕션에서만 활성화하도록 `@Profile` 어노테이션 적용  
- MethodsClient 빈을 MemberInitailizer에 주입  
- MethodsClient 주입 받는 곳에서 봇 토큰 설정하던 것을, 애초에 빈 생성할 때 설정하도록 개선  
<br>
**[서브모듈 레포 PR](https://github.com/2022-pickpick/security/pull/4) 이 머지 된 이후 머지되어야 합니다!!**
<br>  
- Close #244 #214 
<br>
=> refactor: MemberInitializer에 빈 주입 및 테스트에서 비활성화  

backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java, backend/src/main/java/com/pickpick/exception/SubscriptionNotFoundException.java, backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/ui/MessageController.java, backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/controller/MessageControllerTest.java, backend/src/test/java/com/pickpick/message/MessageServiceTest.java, backend/src/test/resources/message.sql
 
메시지 조회 API에 channelId가 전달되지 않을 경우 로직 수정
<br><br>
channelId가 전달되지 않을 경우 memberId로 구독중인 채널들을 조회합니다.
구독 순서 상 최상위의 채널을 기준으로 메시지를 조회합니다.
<br><br>
- Close #255 
<br><br>
=> feat: 메시지 조회 API 에 channelId가 전달되지 않을 경우 로직 수정

backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/ui/dto/MessageResponses.java, backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/controller/MessageControllerTest.java
메시지 조회 시 needPastMessage 함께 응답하도록 수정
<br><br>
- 요청으로 들어온 needPastMessage 그대로 응답에 추가
- 관련 코드 수정 및 테스트코드 보강
<br><br>
@kkojae91 응답에 요청으로 들어온 needPastMessage를 그대로 다시 넘겨주도록 수정했어요.
수정한거 공유하려고 리뷰어로 추가한거고, 아래 이미지처럼 응답이 갈 예정입니다.
혹시 생각하던 방향이 아니라면 말씀주세요!!
<br><br>
- Close #265 
<br><br>
=> feat: 메시지 조회 시 needPastMessage 함께 응답하도록 수정

backend/src/main/java/com/pickpick/auth/support/AuthenticationPrincipal.java, backend/src/main/java/com/pickpick/auth/support/JwtTokenProvider.java, backend/src/main/java/com/pickpick/auth/ui/AuthenticationInterceptor.java, backend/src/main/java/com/pickpick/auth/ui/AuthenticationPrincipalArgumentResolver.java, backend/src/main/java/com/pickpick/channel/ui/ChannelController.java, backend/src/main/java/com/pickpick/channel/ui/ChannelSubscriptionController.java, backend/src/main/java/com/pickpick/config/AuthenticationPrincipalConfig.java, backend/src/main/java/com/pickpick/exception/InvalidTokenException.java, backend/src/main/java/com/pickpick/message/ui/BookmarkController.java, backend/src/main/java/com/pickpick/message/ui/MessageController.java, backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/auth/support/JwtTokenProviderTest.java, backend/src/test/java/com/pickpick/controller/ChannelControllerTest.java, backend/src/test/java/com/pickpick/controller/ChannelSubscriptionControllerTest.java, backend/src/test/java/com/pickpick/controller/MessageControllerTest.java
토큰 인증 및 인가 구현
<br>
- slack OAuth에서 사용자 토큰 받아 정보 확인 후 새로운 토큰 발급 
- ArgumentResolver로 토큰 값 이용  
- 토큰 유효성 검증  
<br>
아직 intercepter를 적용하지 않아 draft로 올립니다  
<br>
- Close #234 
<br><br>
=> feat: 토큰 인증 및 인가 구현

frontend/src/@constants/index.ts, frontend/src/@utils/index.ts, frontend/src/api/auth.ts, frontend/src/api/index.ts, frontend/src/api/utils.ts, frontend/src/components/PrivateRouter/index.tsx, frontend/src/components/PublicRouter/index.tsx, frontend/src/mocks/handlers/auth.ts
사용자 인증 관련 API 연동 및 요청시 실제 토큰 삽입하도록 수정
- 사용자 인증 관련 API 연동  `/api/certification` 연동
- 임시토큰 -> 실제 토큰으로 수정 
- Close #266 
<br><br>
=> feat: 사용자 인증 관련 API 연동 및 실제 토큰 삽입

backend/src/main/resources/appenders/async-file-appender-info.xml
<br><br>
로그백 maxHistory 설정을 5에서 2로 변경합니다.
<br><br>
3차 데모데이 발표시에 사용될 로그 설정 관련 자료 확인차 작업합니다.
기존 5일로 설정했는데 5일 이상 된 파일이 삭제되지 않고 있어서 진행합니다.
<br><br>
=> feat: logback maxHistory 수정. 5 -> 2

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/auth/ui/AuthController.java, backend/src/main/java/com/pickpick/auth/ui/dto/LoginResponse.java, backend/src/main/java/com/pickpick/member/domain/Member.java, backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java, backend/src/test/resources/bookmark.sql, backend/src/test/resources/channel.sql, backend/src/test/resources/member.sql, backend/src/test/resources/message.sql
로그인 시, 응답 body에 최초 로그인 여부를 함께 응답하도록 구성
<br><br>
- Member 엔티티 내 최초 로그인 여부를 구분할 boolean 필드 추가
- AuthService 내 로그인 시, Member 조회하여 최초 로그인 여부 변수 할당 후, markLoggedIn 메서드로 최초 로그인 여부 false 할당
<br><br>
<br><br>
- Close #300 
<br><br>
=> feat: 로그인 시 최초 로그인 여부 응답

backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
북마크 메시지의 유저가 본인으로 보이는 오류 정정
<br>
북마크 메시지의 작성자 본인으로 보이는 오류 정정
북마크를 한 유저의 정보를 담고 있었습니다 😅
<br>
=> hotfix: 북마크 메시지의 유저가 본인으로 보이는 오류 정정

backend/src/main/java/com/pickpick/message/application/MessageService.java
메시지 본문에 작성자 썸네일 주소가 들어가는 오류 수정  
<br>
메시지 본문 텍스트에 작성자 썸네일 주소가 들어가고 있었습니다  
정상적으로 메시지 본문을 담도록 수정했어요  
<br>
=> hotfix: 메시지 본문에 작성자 썸네일 주소가 들어가는 오류 수정

backend/src/main/java/com/pickpick/config/CorsConfig.java
- 운영환경(prod)에선 CORS 설정을 제거합니다
- 로컬, 개발환경에선 CORS 설정을 유지합니다
<br><br>
- CorsConfig 클래스에 `@Profile({"local", "dev"})` 애너테이션 추가
<br><br>
https://www.youtube.com/watch?v=7GaXw-d4fMs
<br><br>
- Close #318
<br><br>
=> feat: local, dev 환경에서만 CORS 허용

backend/src/main/java/com/pickpick/message/application/MessageService.java
https://github.com/woowacourse-teams/2022-pickpick/pull/261
해당 PR에서 받은 피드백 반영했습니다
<br><br>
1. getChannelIds 반복 호출 개선
2. [SubscriptionNotFound 코멘트 답변](https://github.com/woowacourse-teams/2022-pickpick/pull/261#discussion_r935391294)
3. if문 내부 메서드 추출
<br><br>
- https://github.com/woowacourse-teams/2022-pickpick/pull/261
<br><br>
=> refactor: 피드백 반영

backend/build.gradle, backend/src/main/java/com/pickpick/PickpickApplication.java, backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/config/SlackConfig.java, backend/src/main/java/com/pickpick/config/SlackProperties.java
- Slack 관련 정보 객체로 관리
<br><br>
- SlackProperties 객체에서 yaml내 Slack 관련 정보를 주입받아 Bean으로 관리되도록 설정
- Slack 관련 yaml을 직접 Value로 가져가던 코드들을 SlackProperties 객체를 의존하도록 변경
<br><br>
- Close #320
<br><br>
=> feat: Slack 관련 프로퍼티 객체로 관리하도록 적용

backend/src/main/java/com/pickpick/message/application/BookmarkService.java, backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java, backend/src/main/java/com/pickpick/message/ui/BookmarkController.java, backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
북마크 조회, 삭제 api 변경  
<br>
메세지 조회와 포맷이 동일해졌습니다  
**여기의 `id`는 메세지의 `id`입니다**  
다른 점은 배열이 `messages`로 감싸져 있느냐, `bookmarks`로 감싸져 있느냐네요   
GET /api/bookmarks  
authorization: Bearer "token"  
response 200 ok  
```json
{
"bookmarks": [
{
"id" : 23,
"memberId" : 1,
"username" : "써머",
"userThumbnail" : "https://summer.png",
"text" : "Sample Text A",
"postedDate" : "2022-07-17T13:21:55",
"modifiedDate" : "2022-07-17T13:21:55"
}, 
{
"id" : 23,
"memberId" : 1,
"username" : "써머",
"userThumbnail" : "https://summer.png",
"text" : "Sample Text A",
"postedDate" : "2022-07-17T13:21:55",
"modifiedDate" : "2022-07-17T13:21:55"
},
],
"isLast": false
}
```
<br>
DELETE /api/bookmarks?messageId=:messageId  
authroization: Bearer "token"  
response 204 no-content  
쿼리 파라미터 `messageId`에 메세지 `id`가 들어갑니다  
<br>
- …
=> refactor: 북마크 조회, 삭제 api 변경

backend/src/docs/asciidoc/index.adoc, backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
**이 PR은 #355 머지 후에 제가 머지할게요!**  
북마크 API를 RESTdocs에 추가    
<br>
*index.adoc과 BookmarkControllerTest만 포함할 예정이라 둘만 확인하시면 됩니다*
1. 북마크 컨트롤러 슬라이스 테스트를 추가했습니다  
2. 위 테스트로 RESTdocs에 북마크 API를 추가했습니다  
<br>
#355 PR이 선행되어야 해서 불가피하게 해당 PR의 커밋 내역을 그대로 가져왔어요  
해당 PR이 머지되면 정상적으로 이 PR에 해당되는 커밋만 올리도록 할게요~  
<br>
- Close #352 
<br>
=> feat: 북마크 컨트롤러 테스트 및 RESTdocs 추가

frontend/src/api/bookmarks.ts
백엔드에서 변경된 API 명세 반영했습니다.
이제 Feed Page 에서도 북마크 토글 잘 될거예요.
조회 관련 바뀐 부분은, 프론트엔드에서 적용할 부분이 없었습니다. 
```
북마크 삭제 API 
- 이전
/api/bookmarks/bookmarkId
- 현재 
/api/bookmarks?messageId=:messageId
```
- https://github.com/woowacourse-teams/2022-pickpick/pull/355
- Close #359 
<br><br>
=> fix: 변경된 북마크 API 반영

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/auth/ui/AuthController.java, backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
isFirstLogin 응답 오류 수정
<br><br>
첫 로그인 여부를 나타내는 로그인 응답값 필드 `isFirstLogin` 이 항상 true로 반환되던 오류 수정
<br><br>
- https://javabom.tistory.com/103
- 테스트코드에만 Transactional 애너테이션 적용, 프로덕션에선 놓침
- SpringBootTest에서는 Transactional 애너테이션을 제거하고, DatabaseCleaner를 서둘러 도입하면 좋을 것 같습니다
- 연로그가 원인에 대해 미리 알려줘서 수월하게 작업할 수 있었습니다. 그래서 공동작업자로 추가하였습니다
- 커밋이 이상하게 자꾸 추가되어 푸시가 되는데 원인을 잘 모르겠네요 먼저 올라온 PR들 머지되고 나서 다시 살펴보겠습니다
<br><br>
- #321  과 충돌날 것 같아요. #321을 먼저 merge 해주시면 그 뒤에 이 PR을 수정해서 Ready for review로 바꾸겠습니다
- Close #332
<br><br>
=> fix: isFirstLogin이 항상 true로 반환되던 오류 수정

backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java, backend/src/main/java/com/pickpick/slackevent/application/member/MemberJoinService.java, backend/src/main/java/com/pickpick/slackevent/application/member/dto/MemberJoinDto.java, backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java, backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java, backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
- 신규 멤버가 워크스페이스에 조인했을 때 회원 등록 처리 구현
<br><br>
- Slack Event 유형에 MEMBER_JOIN 추가
- Slack으로부터 전달되는 이벤트 컨텍스트까지는 `team_join`으로 표현
- 줍줍 도메인으로 넘어온 이후에는 `MEMBER_JOIN`으로 표현
- MemberJoinService 구현
- MemberJoinServiceTest 구현
- MemberAcceptanceTest 테스트코드 추가
<br><br>
- 워크스페이스에 신규 멤버가 참여했을 때의 이벤트 요청값을 노션에 저장해두었습니다.
- https://www.notion.so/richard7/4-TEAM_JOIN-event-154480a6515e4fbcb4eb9523fc80fb26
<br><br>
- Close #253 
<br><br>
=> feat: TEAM_JOIN 이벤트 구현

backend/src/main/java/com/pickpick/exception/BadRequestException.java, backend/src/main/java/com/pickpick/exception/NotFoundException.java, backend/src/main/java/com/pickpick/exception/channel/ChannelInvalidNameException.java, backend/src/main/java/com/pickpick/exception/channel/ChannelNotFoundException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionDuplicateException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionInvalidOrderException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotExistException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotFoundException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionOrderDuplicateException.java, backend/src/main/java/com/pickpick/exception/member/MemberInvalidThumbnailUrlException.java, backend/src/main/java/com/pickpick/exception/member/MemberInvalidUsernameException.java, backend/src/main/java/com/pickpick/exception/member/MemberNotFoundException.java, backend/src/main/java/com/pickpick/exception/message/BookmarkDeleteFailureException.java, backend/src/main/java/com/pickpick/exception/message/BookmarkNotFoundException.java, backend/src/main/java/com/pickpick/exception/message/MessageNotFoundException.java, backend/src/main/java/com/pickpick/exception/slackevent/SlackEventNotFoundException.java, backend/src/main/java/com/pickpick/exception/slackevent/SlackEventServiceNotFoundException.java
예외 클래스별 클라이언트 메시지 및 해당 메시지 조회 메서드 추가
<br>
이어서 작업할 `InvalidTokenException`을 제외한 커스텀 예외 클래스에 클라이언트 메시지를 추가했습니다  
메시지 추가 외에 변경된 사안입니다  
1.  상속 대상인 `BadRequestException`, `NotFoundException`에 `getClientMessage()`를 정의하고 `override` 하는 구조로 추가했습니다  
원래 각 클래스에서만 추가하려고 했는데, 그렇게 하니 `controllerAdvice`에서 `BadRequestException`, `NotFoundException`로 예외를 캐치하고 있어서 개별 메서드의 `getClientMessage()`를 호출할 수 없었어요 🥲  
그래서 임의로 이런 구조로 추가했는데 더 나은 방안이 떠오르신다면 알려주세요  
2. 예외 클래스가 사용되는 맥락에 따라서 디폴트/클라이언트 메시지를 임의로 수정/작성했습니다  
3. 기존 `String.format~`에 받는 값과 로깅 형식이 일치하지 않는 부분이 있어서 수정했습니다  
예외 메시지 제가 임의로 손댄 게 많아서 되돌리고 싶은 부분, 변경 필요한 부분 있으면 얼마든지 남겨주세요!!  
<br>
- Close #363 
<br>
=> feat: 예외 클래스별 클라이언트 메시지 및 해당 메시지 조회 메서드 추가

frontend/src/@constants/index.ts, frontend/src/@utils/index.ts, frontend/src/Routes.tsx, frontend/src/api/messages.ts, frontend/src/components/Drawer/style.ts, frontend/src/components/SearchForm/index.tsx, frontend/src/components/SearchForm/style.ts, frontend/src/components/SearchInput/index.tsx, frontend/src/components/SearchInput/style.ts, frontend/src/components/SearchOptions/index.tsx, frontend/src/hooks/useModal.ts, frontend/src/hooks/useSearchKeywordForm.ts, frontend/src/hooks/useSelectChannels.ts, frontend/src/pages/Feed/index.tsx, frontend/src/pages/SearchResult/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
검색 기능 API 연동 및 SearchResult Page 개발
<br><br>
- useChannelIds hook 네이밍 변경 -> useSelectChannels
- SearchForm component 개발
- SearchInput, SearchOptions button type 설정 및 스타일 변경
- SearchForm component Feed, SpecificDateFeed page component에 적용
- SearchResult component Routes 연결 및 PATH_NAME 상수화
- getMessages API 명세에 맞게 keyword 추가
- convertSeparatorToKey util 함수 작성
- SearchResult page component 개발
- useModal hook useEffect clean up callback 함수 작성
- scroll hidden -> auto 로 변경하는 clean up callback 함수 작성
- useSearchKeywordForm custom hook 으로 form 관련 로직 분리
<br><br>
이야기 했던 것 처럼 기존에 SearchInput, SearchOptions로 구성되어 있던 것을 SearchForm Component로 추출 후 API 연동을 진행했습니다.
SearchResult page Component를 생성했으니 확인해주시면 감사하겠습니다.
이슈를 따로 만들까 하다 이번 커밋에 useModal hook안에 useEffect clean up 함수가 작성되어 있지 않아 스크롤이 고장나는 이슈가 있어 …
=> feat: 검색 기능 API 연동 및 SearchResult Page 개발

backend/src/main/java/com/pickpick/auth/support/JwtTokenProvider.java, backend/src/main/java/com/pickpick/exception/auth/ExpiredTokenException.java, backend/src/main/java/com/pickpick/exception/auth/InvalidTokenException.java, backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java, backend/src/test/java/com/pickpick/auth/support/JwtTokenProviderTest.java
**#367 이 머지되면 해당하는 커밋만 남겨서 제가 머지할게요! approve만 해주세요!** 
`InvalidTokenException` 클래스로만 발생하는 토큰 예외 처리를 `ExpiredTokenException`로 추가 분리
<br>
기존 인증/인가를 추가하면서 유효 시간이 지난 토큰도 `InvalidTokenException`으로 처리했었는데요,  
이를 `ExpiredTokenException`으로 분리했습니다  
테스트 코드에서도 메시지 문자열 검사를 삭제했어요~   
<br>
- Close #364 
<br>
=> feat: 만료된 토큰 예외 처리 클래스 분리  

backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/pickpick/exception/message/ReminderDeleteFailureException.java, backend/src/main/java/com/pickpick/message/application/ReminderService.java, backend/src/main/java/com/pickpick/message/domain/Reminder.java, backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java, backend/src/main/java/com/pickpick/message/ui/ReminderController.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java, backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
메시지 리마인더 삭제 API 구현
<br><br>
-  메시지 리마인더 삭제 API 구현
- 관련 테스트코드 작성
- RestDocs 에 리마인더 삭제 api 추가
<br><br>
- 리마인더 생성 API 구현 후 테스트코드 수정 예정
<br><br>
- Close #383 
<br><br>
=> feat: 메시지 리마인더 삭제 API 구현

backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
메세지 조회 시 북마크 join으로 함께 조회
<br>
- 기존 20개의 메세지 조회 시 1개의 멤버 조회 + 20개의 북마크 조회 쿼리를 추가 실행 후 붙였습니다🥲  
- 이제 한 번의 쿼리로 북마크 여부도 함께 조회해와요!  
💡 Querydsl을 통해 조회해올 때 `ui` 패키지 하위의 `MessageResponse`를 쓰는 대신 별도의 `DTO`를 써야 하나 고민중입니다  
우선 `ui`의 `dto`를 서비스 레이어의 로직에서 활용하고 있는게 문제같아 보이고요,  
`MessageResponse`에 `Querydsl` 패키지가 `import` 되는 것도 문제라고 여겨져요  
반면에 결국 같은 데이터를 다룰텐떼 굳이 분리해서 내용물 그대로 갈아끼우는 행위가 괜찮을까? 싶기도 합니다  
저는 `MessageDto` 같은 이름으로 분리하고 싶다 쪽인데 여러분의 의견이 궁금해요 😁  
<br>
- Close #347 
<br>
=> refactor: 메세지 조회 시 북마크 join으로 함께 조회

backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/pickpick/exception/message/ReminderUpdateFailureException.java, backend/src/main/java/com/pickpick/message/application/ReminderService.java, backend/src/main/java/com/pickpick/message/domain/Reminder.java, backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java, backend/src/main/java/com/pickpick/message/ui/ReminderController.java, backend/src/main/java/com/pickpick/message/ui/dto/ReminderRequest.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java, backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
메시지 리마인더 등록 및 수정 API 구현
<br><br>
- 메시지 리마인더 등록 api 추가 (`POST /api/reminders`)
- 메시지 리마인더 수정 api 추가 (`PUT /api/reminders`)
- 위 API에 대한 Service, controller, acceptance test 추가
- RestDocs에 해당 API 명세 작성
<br><br>
- Close #386 
- Close #387
<br><br>
=> feat: 메시지 리마인더 등록 및 수정 API 구현

.github/workflows/frontend-lighthouse-ci.yml, frontend/lighthouserc.js
프론트엔드 lighthouse-ci 적용
- lighthouserc.js 설정 파일 작성 
-  아주 기본적인 셋팅만 해놓은 상태입니다.  
- github action 실행을 위한 yml 파일 추가 
- PR 시에만 동작하도록 했습니다. 추후 필요시 push 시에도 동작 하는 스크립트도 추가하겠습니다.
- 현재는 로그인 필요 페이지는 검사 하지 못하고, 랜딩페이지만 검사합니다. (추후 디벨롭할게요.)
액션 트리거는 `develop, main, realease 브랜치` 에 `frontend 디렉토리 내부 변경이 있을 때`, `Pull Request` 가 올라왔을 때 입니다.
1. 깃헙 액션이 프론트엔드 정적 파일을 build 합니다.
2. build 된 결과물을 lighthouse ci 를 사용하여 lighthouse 검사를 실행합니다.
3. 실행된 검사의 결과물을 github action 이 해당 pr 의 코멘트로 아래와 같이 남겨줍니다.
- Close #392 
<br><br>
=> feat: 프론트엔드 lighthouse-ci 적용

backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java, backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
전달된 메시지 생성 이벤트가 메시지 댓글 생성일 시 저장하지 않고 early return 처리
<br>
`event` 필드 내에 `thread_ts` 값이 존재할 시, 메시지의 댓글(스레드) 생성 이벤트입니다  
논의 결과 저장하지 않기로 했기에 `early return`으로 저장하지 않고, 테스트를 추가했습니다  
인수테스트는 똑같이 `200`응답 처리가 될 거라 따로 케이스 추가하지 않았습니다 🤔 
<br>
- Close #397 
<br>
=> feat: 메시지 댓글 이벤트 전달 시 저장 제외

backend/src/main/java/com/pickpick/channel/domain/ChannelRepository.java, backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java, backend/src/main/java/com/pickpick/member/domain/MemberRepository.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java, backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java, backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java, backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java, backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java, backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
Channel, Member 도메인 하위 레포지토리 save() 반환형을 해당 엔티티 클래스로 수정  
<br>
- ChannelRepository
- ChannelSubscriptionRepository
- MemberRepository
해당 클래스들의 `save()` 반환형을 엔티티 클래스로 변경하고, 사용하는 코드도 찾아 수정했습니다  
<br>
`Message` 도메인 하위는 리마인더 작업과 충돌날 것 같아서 끝나고 할게요  
<br>
- #405 
<br>
=> refactor: Channel, Member 도메인 하위 레포지토리 save() 반환형 수정  

backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java, backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java, backend/src/test/resources/message.sql
메시지 조회 시 isSetReminded 필드 추가
<br><br>
- 메시지 조회 시 isSetReminded 필드 추가
- 관련 서비스 테스트, 인수 테스트 케이스 추가
- 컨트롤러 테스트 수정
- 깨지는 테스트 케이스 수정
<br><br>
- 코멘트 달아주시면 확인 후 직접 merge하겠습니다!
<br><br>
- Close #389
<br><br>
=> feat: 메시지 조회 시 isSetReminded 필드 추가

frontend/src/components/PublicRouter/index.tsx, frontend/src/hooks/useModeTheme.ts
로그인 되지 않은 사용자에게 랜딩페이지에서 에러메시지를 띄우는 버그 해결 
- 로그인 되지 않은 사용자에게 랜딩페이지에서 에러메시지를 띄우는 버그 해결  (PublicRouter 수정)
- OS 환경 설정값 상관 없이 사용자가 light mode 세팅했으면 light mode 로 보여주도록 수정 
- PublicRouter 에서는 400 에러가 나도, 에러메시지가 보여지지 않아야 하므로 전역의 onError 핸들러가 오버라이드 되도록 빈 함수를 주입했습니다.
- Close #418 
<br><br>
=> fix: 로그인 되지 않은 사용자에게 랜딩페이지에서 에러메시지를 띄우는 버그 

backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java, backend/src/main/java/com/pickpick/message/domain/MessageRepository.java, backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java, backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
message 도메인 하위 repository의 save 메서드에서 void 대신 해당 도메인 반환하도록 변경했습니다  
<br>
이제 아래 레포지토리들은 해당 도메인을 반환합니다   
- MessageRepository (Message)
- BookmarkRepository (Bookmark)
- ReminderRepository (Reminder)
<br> 
테스트도 이에 맞춰 코드를 인라인 처리했습니다  
<br>  
- Close #405 
<br><br>
=> feat: message 도메인 하위 repository에서 save시 해당 도메인 반환하도록 변경

backend/src/main/java/com/pickpick/message/application/MessageService.java
메시지 목록 조회 시 해당 회원의 북마크만 조회합니다  
<br>
기존에 해당 회원 조회 조건을 안걸어서, 누가 한 것이든 북마크가 존재만 한다면 `isBookmarked: true`로 나가고 있었습니다  
이를 해당 회원의 북마크만 조회하도록 수정했습니다  
<br>
- Close #408 
<br>
=> fix: 메시지 조회 시 해당 회원의 북마크일 경우만 isBookmarked: true 반환  

backend/src/main/java/com/pickpick/message/application/ReminderService.java, backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponse.java
리마인더 조회 시 메시지 작성자의 정보 전달
<br><br>
(1)
리마인더 조회 시 리마인더를 등록한 사용자의 정보를 가져오고 있었습니다.
메시지를 등록한 사용자의 정보를 가져올 수 있도록 수정했습니다.
(2)
불필요한 join을 제거했습니다.
<br><br>
- Close #431 
<br><br>
=> fix: 리마인더 조회 시 메시지 작성자의 정보 전달

backend/src/docs/asciidoc/index.adoc
리마인더 삭제 api 명세가 북마크 삭제 api 명세로 보였던 에러 수정
<br><br>
**BEFORE**
**AFTER**
<br><br>
- 위의 사진 다크모드인건 신경 안쓰셔도 됩니다! 인텔리제이에서 바로 열면 저렇게 안예쁜 디자인으로 나와요.
<br><br>
- Close #434 
<br><br>
=> fix: 리마인더 삭제 api 명세가 북마크 삭제 api 명세로 보였던 에러 수정

backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java, backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java, backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
file_share 이벤트를 저장하는 기능 구현
<br><br>
- file_share 이벤트 저장 기능 구현
- SlackEvent test 추가
- Acceptance test 추가
<br><br>
- 기존에 작성했던 file_share 이벤트 코드와 동일합니다.
- 기존 코드에 SlackEventTest, MessageEventAcceptanceTest만 추가했습니다.
- 기존 코드 및 리뷰는  #225 에서 확인하실 수 있습니다!
- createChannel은 이 PR과 #424 PR이 머지되면 진행하겠습니다.
<br><br>
- Close #425 
<br><br>
=> feat: file_share 이벤트를 저장하는 기능 구현

backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java, backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java
메시지 조회 시 remindDate 필드 추가
<br><br>
- 메시지 조회 시 remindDate 추가
- 테스트 케이스 추가
<br><br>
- remindDate 값이 없으면 null로 전달
<br><br>
- Close #438 
<br><br>
=> feat: 메시지 조회 시 remindDate 필드 추가

.github/workflows/backend-sonarqube.yml, backend/build.gradle
- SonarQube 연동
<br><br>
- `build.gradle` 에 `jacoco`, `sonarqube` 관련 설정 추가
- Github Repository Secrets에 SONAR_TOKEN, SONAR_HOST_URL 추가
- Github Actions에 Sonarqube 관련 수행 명령 추가
<br><br>
- [Sonarqube PR Decoration 적용기](https://github.com/woowacourse-teams/2022-pickpick/wiki/Sonarqube-PR-Decoration-%EC%A0%81%EC%9A%A9%EA%B8%B0)
- 현재, Github Actions Secret 값이 제대로 설정되어 있지 않아서 Check Fail로 나오고 있습니다.
- 시뮬레이션 영상 제작 과정에서 Secret 값이 변경되어 그렇습니다.
- 다같이 진행해서 프로덕션용으로 구축한 다음 그 값을 넣어주면 정상 동작할 겁니다.
<br><br>
- Close #336
- Close #341
<br><br>
=> chore: Jacoco, SonarQube 연동

backend/src/main/java/com/pickpick/config/ControllerAdvice.java, backend/src/main/java/com/pickpick/config/dto/ErrorResponse.java, backend/src/main/java/com/pickpick/exception/BadRequestException.java, backend/src/main/java/com/pickpick/exception/NotFoundException.java, backend/src/main/java/com/pickpick/exception/auth/InvalidTokenException.java, backend/src/main/java/com/pickpick/exception/channel/ChannelNotFoundException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionDuplicateException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionInvalidOrderException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotExistException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotFoundException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionOrderDuplicateException.java, backend/src/main/java/com/pickpick/exception/member/MemberNotFoundException.java, backend/src/main/java/com/pickpick/exception/message/BookmarkDeleteFailureException.java, backend/src/main/java/com/pickpick/exception/message/BookmarkNotFoundException.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
400, 401 발생 시 코드와 메세지를 가진 ErrorResponse 반환  
<br>
- 에러 코드를 예외별 필드에 추가  
- 해당 에러 코드와 클라이언트 메시지를 담은 `ErrorResponse` 객체를 `ControllerAdvice`에서 반환  
<br>
급한 사안 같아서 프론트 코드를 보고 **현재 프론트에서 처리 중인 에러코드** 만 작업했습니다  
일단 이거부터 머지하고 나머지 추가하면 어떨까요?   
마지막에 `approve` 하시는 분이 머지해주세요!! (급해서!!) 
<br>
- Close #450 
<br><br>
=> feat: 코드와 메세지를 가진 ErrorResponse 반환  

frontend/public/index.html, frontend/webpack.common.js
- htmlWebpackPlugin 사용하여, HTML에 로컬 이미지가 함께 빌드되도록 추가
- 제대로 동작하지 않는 og image 태그 삭제
- Close #452 
<br><br>
=> fix: 배포된 페이지에서 favicon 누락 해결

frontend/src/@types/shared.ts, frontend/src/App.tsx, frontend/src/hooks/useApiError.ts
서버 에러 대응 방법 수정 및 구독중인 채널 없을 경우 대응
- 서버에서 내려주는 에러 코드를 사용하기 위해서 에러 타입 수정
- 구독 중인 채널 없다는 에러일 경우, 채널 추가 페이지로 라우팅 되도록 수정 
<br><br>
- Close #455 
<br><br>
=> fix: 서버 에러 대응 방법 수정 및 구독중인 채널 없을 경우 대응

backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java, backend/src/test/java/com/pickpick/channel/ui/ChannelControllerTest.java, backend/src/test/java/com/pickpick/channel/ui/ChannelSubscriptionControllerTest.java, backend/src/test/java/com/pickpick/config/DatabaseCleaner.java, backend/src/test/java/com/pickpick/config/RestDocsTestSupport.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java, backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java, backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java, backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
- 테스트 격리를 위한 DatabaseCleaner 추가
<br><br>
- 테스트 패키지 내 DatabaseCleaner 클래스 추가
- AcceptanceTest 클래스에 DatabaseCleaner 의존성 주입 및 AfterEach에 호출
- build.gradle 내 guava 라이브러리 추가
<br><br>
- https://tecoble.techcourse.co.kr/post/2020-09-15-test-isolation/
- https://github.com/woowacourse-teams/2021-pick-git/blob/develop/backend/pick-git/src/test/java/com/woowacourse/pickgit/config/DatabaseConfigurator.java
- 인수 테스트에 truncate 를 제거하고 테스트했을 때 3가지 정도 깨지는 케이스가 있었습니다.
- 두 가지 방법이 있어서 의견 교환을 위해 우선 PR 생성해둡니다.
- 방향성 합의가 완료되면 테스트 truncate.sql 모두 제거하고도 테스트 깨지지 않는 점만 확인하고, 수정은 당장 하지 않고 머지 하고 단계적으로 진행하면 어떨까 싶습니다.
<br><br>
- Close #254
<br><br>
=> feat: DatabaseCleaner 구현

backend/src/main/java/com/pickpick/channel/application/ChannelService.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java, backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
채널 생성 역할을 channelService에게 위임
<br><br>
<br><br>
- MessageCreatedService, MessageThreadBroadcastService, MessageFileShareService 세 곳에 중복으로 존재하던 createChannel 로직을 channelService 로 이동했습니다.
- ChannelServiceTest를 만들었습니다.
<br><br>
- Close #426 
<br><br>
=> refactor: 채널 생성 역할을 channelService에게 위임

backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java, backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
북마크 탭에서 북마크 조회 시 북마크 아이디가 필요한데 현재 서버에서 북마크 아이디를 보내주고 있지 않아서 bookmark를 더이상 조회할 수 없는 에러 발생
<br><br>
BookmarkResponse 내부의  {id: 메시지 아이디} 였는데,
{id : 북마크아이디,
messagdId: 메시지아이디}로 수정
(id를 메시지 아이디가 아니라 북마크 아이디로 수정하고, messageId 필드를 추가)
<br><br>
<br><br>
- Close #474
<br><br>
=> fix: BookmarkResponse에서 bookmark id 도 함께 반환받도록 수정

backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java, backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
thread_broadcast 메시지 수정 시 수정이 반영되지 않는 버그 수정
<br><br>
- MessageThreadBroadcastService 내부 로직 수정
- MessageThreadBroadcastServiceTest 수정
<br><br>
- 궁금한거 댓글에 하나 달아놨어요!
- 제가 머지하겠습니다
<br><br>
- Close #456 
<br><br>
=> fix: thread_broadcast 메시지 수정 시 수정이 반영되지 않는 버그 수정

backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java
`MemberAcceptanceTest` 내 `@Disabled`된 테스트를 삭제했습니다  
구동 시점에 전체 멤버 조회 시, 저장된 멤버가 있는지 검사하는 테스트였습니다 
<br>
- Close #483 
<br>
=> refactor: MemberAcceptanceTest 내 @Disabled된 테스트 삭제

backend/src/main/java/com/pickpick/member/application/MemberInitializer.java
MemberInitializer 예외를 프로젝트 예외로 변환  
기존에는 슬랙이 던진 `SlackApiException`, `IOException`을 그대로 다시 던졌습니다 
이를 프로젝트 예외인 `SlackApiCallException`으로 변환해 `ControllerAdvice`에서 처리 가능하도록 개선했습니다  
<br>
`SlackApiCallException`의 경우 로깅용 메시지를 남기지 않고 있습니다  
어떤 상황에서 호출에 실패했는지 남기는 게 어떨까요?  
이 예외는 프론트에 전달되지 않으니까 코드, 클라이언트 메시지가 없어도 충분할 것 같네요  
```java
// NotFound 예외 클래스 
public class NotFoundException extends RuntimeException {
private static final String ERROR_CODE = "NOT_FOUND";
private static final String CLIENT_MESSAGE = "해당 정보를 조회하지 못했습니다.";
public NotFoundException(final String message) {
super(message);
}
...
```
```java
// SlackApiCall 예외 클래스 
public class SlackApiCallException extends RuntimeException {
public SlackApiCallException(final Exception e) {
super(e);
}
...
```
<br>
- Close #486 
<br>
=> refactor: MemberInitializer 예외를 프로젝트 예외로 변환  

backend/src/main/java/com/pickpick/auth/support/AuthorizationExtractor.java, backend/src/main/java/com/pickpick/auth/ui/AuthController.java, backend/src/main/java/com/pickpick/auth/ui/AuthenticationInterceptor.java, backend/src/main/java/com/pickpick/auth/ui/AuthenticationPrincipalArgumentResolver.java
`AuthorizationExtractor`를 `auth/supprot` 패키지로 이동
<br>
`AuthorizationExtractor`를 이동시켰습니다
`pickpick/utils` -> `pickpick/auth/supprot`  
<br>
#503 
<br>
=> refactor: AuthorizationExtractor를 auth 패키지로 이동

backend/src/main/java/com/pickpick/slackevent/application/SlackEventServiceFinder.java
SlackEventServiceFinder 내부 필드인 List<SlackEventService>의 접근제어자를 public에서 private으로 수정
<br><br>
SlackEventServiceFinder 내부 필드인 List<SlackEventService>의 접근제어자를 public에서 private으로 수정
<br><br>
- Close #511 
<br><br>
pr 올리기 머쓱하네요 😵‍💫
=> refacotor: 접근제어자 수정

backend/src/main/java/com/pickpick/message/application/BookmarkService.java, backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/application/ReminderService.java, backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponses.java, backend/src/main/java/com/pickpick/message/ui/dto/MessageResponses.java, backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponses.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java, backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java, backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java, backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java, backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java, backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
메시지/북마크/리마인더 조회 API 스펙을 일괄 변경했습니다
- `isLast`가 `hasPast, hasFuture`로 나뉘어졌습니다  
<br>
메시지 조회 시 
- 더 과거의 메시지가 
- 조회 가능(존재)할 때 `"hasPast": "true"`
- 조회 불가(존재하지 않음)일 때 `"hasPast": "false"`
- 더 미래의 메시지가
- 조회 가능(존재)할 때 `"hasFuture": "true"`
- 조회 불가(존재하지 않음)일 때 `"hasFuture": "false"`
- `isNeedPastMessage`는 변동없고 무관합니다 
북마크 조회 시
- 더 과거의 북마크가 
- 조회 가능(존재)할 때 `"hasPast": "true"`
- 조회 불가(존재하지 않음)일 때 `"hasPast": "false"`
리마인더 조회 시 
- 더 미래의 리마인더가
- 조회 가능(존재)할 때 `"hasFuture": "true"`
- 조회 불가(존재하지 않음)일 때 `"hasFuture": "false"`
<br>
북마크 조회 정렬 기준 변경은 별도 테스크로 가져가길 희망합니다
하지만 프론트 쪽에서 같이 작업하는 게 편하다면 추가 개발해서 여기에 올리겠습니다  
<br>
- Close #484 
<br>
=> refactor: 메시지/북마크/리마인더 조회 API 스펙 변경  

frontend/src/hooks/useScrollToTop.ts, frontend/src/pages/Bookmark/index.tsx, frontend/src/pages/Feed/index.tsx, frontend/src/pages/Reminder/index.tsx, frontend/src/pages/SpecificDateFeed/index.tsx
최상단으로 스크롤을 움직이는 로직 리팩터링 
```tsx
import { useEffect } from "react";
interface Props {
dependencies?: unknown[];
}
function useScrollToTop({ dependencies = [] }: Props = {}) {
useEffect(() => {
window.scrollTo({
top: 0,
});
}, dependencies);
}
export default useScrollToTop;
```
- 위와 같은 useScrollToTop 훅을 작성하여 적용하였습니다.
- useEffect 에 의존성 배열 주입이 필요한 경우가 있어서 dependencies 를 옵셔널 Props 로 받도록 구현했습니다.
- Bookmark, Feed, SpecificDateFeed, Reminder 페이지에 적용했습니다.
- Close #523 
<br><br>
=> refactor: 최상단으로 스크롤을 움직이는 로직 리팩터링 

backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java, backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java, backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java, backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
쿼리에서 불필요한 left outer join을 제거합니다.
<br><br>
[노션 페이지](https://www.notion.so/findByObject-vs-findByObjectId-cecf5fb30cac41e7883783e119693a4b)에 Repository 단에서 불필요한 left outer join이 일어나는 쿼리들과 해당 쿼리들을 어떻게 수정했는지, 수정하지 않았다면 왜 수정하지 않았는지에 대해서 정리해뒀습니다!
<br><br>
노션 페이지 내부에 기록한 내용인데, 
channelSubscriptionRepository의 findFirstByMemberIdOrderByViewOrderAsc(Long memberId)쿼리를 개선하지 않은 이유에 대해서 써놨는데, 연로그와 써머의 의견도 들어보고싶습니다!
그리고 각 쿼리를 개선한 것에 대해서 `이 쿼리는 이렇게 개선하는 것 보다 다른 방법이 더 좋을 것 같다!`, `이 쿼리는 굳이 개선하지 않아도 좋을 것 같다` 등 여러가지 의견 모두 환영합니다.
그리고 대부분 @Query를 이용해서 해결했는데, 이 해결방법 자체가 괜찮은지도 의견이 궁금합니다.
<br><br>
- Close #526 
<br><br>
=> refactor: 쿼리에서 불필요한 left outer join 삭제

frontend/src/components/@layouts/Navigation/index.tsx, frontend/src/components/Dropdown/index.tsx, frontend/src/hooks/useOuterClick.ts
<br><br>
Drawer 내부 클릭시 Drawer 가 닫히는 문제 해결했습니다.
이를 해결하기 위해서는 ..`useOuterClick` 을 수정했어야 했습니다. 😭 
원래는 innerRef 를 Drawer 컴포넌트에도 붙여주면 될 거라고 생각했지만,
그럴 경우 innerRef 2개를 저장해야 하지만 하나만 저장해서 제대로 동작하지 않았습니다.
그래서 innerRef 를 Array 형식으로 변경해야했습니다.
- 클릭해도 닫히지 않는 영역이 2개 이상이어야 할 경우 ref 가 2개여야 했습니다..
- 이를 좀 더 범용적으로 사용하기 위해서, 닫히지 않는 영역의 갯수를 props 로 받고, 갯수 만큼 innerRef를 생성하여 반환하도록 했습니다. 
```ts
import { useEffect, useRef } from "react";
type CallbackType = () => void;
interface Props {
callback: CallbackType;
requiredRefCount?: number; // 눌러도 닫히지 않는 영역의 갯수. 디폴트는 1개 
}
function useOuterClick({ callback, requiredRefCount = 1 }: Props) {
const callbackRef = useRef<CallbackType>();
const innerRefArray = [...Array(requiredRefCount || 1)].map(() =>
useRef<HTMLDivElement>(null)
);
callbackRef.current = callback; …
```
=> fix: Drawer 내부 클릭 시, Drawer 가 닫히는 문제 해결

backend/src/main/java/com/pickpick/exception/BadRequestException.java, backend/src/main/java/com/pickpick/exception/NotFoundException.java, backend/src/main/java/com/pickpick/exception/auth/ExpiredTokenException.java, backend/src/main/java/com/pickpick/exception/auth/InvalidTokenException.java, backend/src/main/java/com/pickpick/exception/channel/ChannelInvalidNameException.java, backend/src/main/java/com/pickpick/exception/channel/ChannelNotFoundException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionDuplicateException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionInvalidOrderException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotExistException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotFoundException.java, backend/src/main/java/com/pickpick/exception/channel/SubscriptionOrderDuplicateException.java, backend/src/main/java/com/pickpick/exception/member/MemberInvalidThumbnailUrlException.java, backend/src/main/java/com/pickpick/exception/member/MemberInvalidUsernameException.java, backend/src/main/java/com/pickpick/exception/member/MemberNotFoundException.java, backend/src/main/java/com/pickpick/exception/message/BookmarkDeleteFailureException.java, backend/src/main/java/com/pickpick/exception/message/BookmarkNotFoundException.java, backend/src/main/java/com/pickpick/exception/message/MessageNotFoundException.java, backend/src/main/java/com/pickpick/exception/message/ReminderDeleteFailureException.java, backend/src/main/java/com/pickpick/exception/message/ReminderNotFoundException.java, backend/src/main/java/com/pickpick/exception/message/ReminderUpdateFailureException.java, backend/src/main/java/com/pickpick/exception/slackevent/SlackEventNotFoundException.java, backend/src/main/java/com/pickpick/exception/slackevent/SlackEventServiceNotFoundException.java, backend/src/main/java/com/pickpick/exception/utils/InvalidJsonRequestException.java
Exception 내부에 ErrorCode 필드가 빠진 것 수정
<br><br>
- 정의되어있는 CustomException에 ErrorCode 필드 빠진 곳 채워줌
- CustomException내부 DEFAULT_MESSAGE => SERVER_MESSAGE로 이름 변경
- CustomException 내부에서 Getter 제거 (ControllerAdvice에서 부모의 게터를 사용하므로 제거)
현재 존재하는 Custom Exception에 빠진 ErrorCode를 추가하는 것 뿐만 아니라 앞으로 새로 생길 Custom Exception에 대해서도 개발자에게 강제할 수 있도록 코드 수정
- `NotFoundException`, `BadRequestException`에 상수를 필드로 변경
- `NotFoundException`, `BadRequestException` 생성자를 수정하여 자식 Exception에서 ErrorCode, ClientMessage 선언 강제
<br><br>
머지된 후 작업할 것 / 생각할 것
- repository에서 default 메서드 사용
- DebugMessage 객체 도입에 대해서 고민해보기
<br><br>
- Close #557 
<br><br>
=> refactor: Exception 내부에 ErrorCode 필드가 빠진 것 수정

backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/RestHandler.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthHandler.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthRestHandler.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java, backend/src/test/resources/application.yml
- 인수 테스트 코드 구조 변경
- 인증인가 인수테스트 리팩터링
<br><br>
1. JPA, H2 로그 on/off 설정 가능
- `application.yml`에서 $log-option 참고
2. Rest API 로그 on/off 설정 가능
- `RestHandler`의 request 메서드 참고
- `application.yml`의 `log` 값이 true이면 콘솔에 로그가 남음
3. `@MockBean`, `@SpyBean`을 `AcceptanceTest`에서 주입
- 모든 AcceptanceTest가 테스트 컨텍스트 공유
1. `RestHandler` 생성
- Rest 요청을 보내주는 `RestHandler` 생성
- `AcceptanceTest`에서는 어떤 코드를 보내는지 보는게 아니라 어떤 행위를 하는지만 보여줌
- 전체: `RestHandler` 적용
- `AuthAcceptanceTest`: `@Sql` 제거 
<br><br>
인수 테스트 전체 구조에 변경 사항이 생겨서 files changed가 좀 많은데요
`AcceptanceTest`, `RestHandler`, `AuthAcceptanceTest` 이 세 개만 봐주시면 될 것 같아요😃
<br><br>
- Close #565
<br><br>
=> test: 인수 테스트 코드 구조 변경 및 인증인가 인수테스트 리팩터링

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java, backend/src/main/java/com/pickpick/channel/domain/ChannelRepository.java, backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java, backend/src/main/java/com/pickpick/member/domain/MemberRepository.java, backend/src/main/java/com/pickpick/message/application/BookmarkService.java, backend/src/main/java/com/pickpick/message/application/MessageService.java, backend/src/main/java/com/pickpick/message/application/ReminderService.java, backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java, backend/src/main/java/com/pickpick/message/domain/MessageRepository.java, backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java, backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelRenameService.java, backend/src/main/java/com/pickpick/slackevent/application/member/MemberChangedService.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageChangedService.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java, backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
Repository 인터페이스 내부에 예외를 던지는 default 메서드 추가
<br><br>
Repository 인터페이스 내부에 예외를 던지는 default 메서드 추가
- `get~` 으로 시작하는 디폴트 메서드를 만들었습니다/
<br><br>
의견을 묻고싶은게 있어요.
현재 Optional로 반환하는 메서드 중 
1. `subscriptions.findFirstByMemberIdOrderByViewOrderAsc()`
2. `bookmarks.findByMemberIdAndMessageId()`
이 두 개는 아직 디폴트 메서드를 만들어주지 않았습니다.
1번은 뭔가 특정 값으로만 조회하는게 아니라 정렬하는 조건까지 있어서 고민이 되더라고요. 프로덕션 코드에서 SubscriptionNotFoundException을 throw 해줘서 괜찮을까 싶다가도, 정렬조건까지 메서드명에 담겨있어서 살짝 고민이 됩니다.
2번은 프로덕션 코드에서 사용할 때 BookmarkDeleteFailureException을 throw해줍니다. BookmarkNotFoundException을 throw 해주는게 아니라서 디폴트 메서드 내부에서 사용하는게 좋지 않을 것 같아 고민입니다.
저는 `XXXXNotFoundException`을 던져주는 경우라면 조회 조건과 상관없이 repository 내부에 디폴트 메서드를 정의하면 어떨까? 라고 생각했는데 써머와 연로그의 의견도 궁금합니다 👍 
----------------------------------------------------------------------------------- …
=> refactor: Repository 인터페이스 내부에 예외를 던지는 default 메서드 추가

backend/src/docs/asciidoc/index.adoc, backend/src/test/java/com/pickpick/support/DocsControllerTest.java, backend/src/test/java/com/pickpick/support/ErrorCodeController.java, backend/src/test/java/com/pickpick/support/ErrorCodeDocsTest.java, backend/src/test/java/com/pickpick/support/ErrorCodeSnippet.java, backend/src/test/resources/org/springframework/restdocs/templates/error-code-template.snippet
Rest Docs 에 에러코드 추가
<br><br>
- 컨트롤러 테스트 리팩토링을 하면서 Docs에 에러코드를 정리했습니다.
- 에러코드를 직접 하나하나 작성하는 것보다, CustomException을 만들면 자동으로 RestDocs에 에러코드가 추가되면 좋을 것 같아 리플렉션을 활용했습니다. 
- NotFoundException과 BadRequestException을 상속한 하위 커스텀 익셉션 내부에 `ERROR_CODE` 필드와 `CLIENT_MESSAGE` 필드가 없으면 테스트가 실패합니다.
- NotFoundException과 BadRequestException은 `ERROR_CODE` 필드와 `CLIENT_MESSAGE` 필드가 없어도 테스트 통과하도록 했습니다.
RestDocs에 하단 이미지처럼 추가됩니다.
intellij에서 연 파일이라 다크모드가 적용되어서 안예뻐보이네요 ㅠㅠ
<br><br>
- 컨트롤러 테스트 개선과 같이 작업했었는데, PR 단위가 너무 커서 PR을 분리했습니다.
<br><br>
- Close #572
<br><br>
=> feat: RestDocs 에 에러코드 추가

backend/src/main/java/com/pickpick/auth/support/AuthorizationExtractor.java, backend/src/main/java/com/pickpick/exception/auth/ExtractTokenFailException.java, backend/src/test/java/com/pickpick/acceptance/AcceptanceTestBase.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java, backend/src/test/java/com/pickpick/channel/ui/ChannelControllerTest.java, backend/src/test/java/com/pickpick/channel/ui/ChannelSubscriptionControllerTest.java, backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java, backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java, backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java, backend/src/test/java/com/pickpick/support/DocsControllerTest.java, backend/src/test/java/com/pickpick/support/DocsControllerTestBase.java, backend/src/test/java/com/pickpick/support/ErrorCodeDocsTest.java
code smell 최소화
<br><br>
소나큐브의 code smell 최소화
- 모든 메서드가 static인 클래스에서 private 빈 생성자 private 생성
- RuntimeException 제거
- 테스트 클래스에서 불필요한 public 제거
- assertThatThrownBy 시 런타임 예외가 발생할 수 있는 경우를 1개로 제한
- 인수테스트, 컨트롤러 테스트의 부모 클래스 이름 변경
- 사용하지 않는 결과값 제거
<br><br>
=> refactor: code smell 최소화

backend/src/main/java/com/pickpick/member/domain/Member.java, backend/src/main/java/com/pickpick/workspace/domain/Workspace.java
토큰 타입 varchar(64) -> varchar(256) 로 수정
<br><br>
- member와 workspace 엔티티에서 토큰의 타입을 수정했습니다.
- dev DB의 Member 와 Workspace 에서 token 칼럼의 타입을 varchar(64) -> varchar(256)으로 수정했습니다.
<br><br>
이런 예외가 발생하더라고요.
그리고 https://api.slack.com/changelog/2016-08-23-token-lengthening 2016년의 슬랙 글이긴한데, 이 떄 한 번 토큰이 길어졌다고 하더라고요. 지금 당장은 varchar(128)로도 충분하긴한데, 문서 내부에서 `앞으로 슬랙에서 256까지 확대할 계획이 있으니 255길이의 칼럼을 사용하는것을 추천한다`라고 되어있어서, varchar(256)으로 수정했습니다!
+) DB 칼럼 계속 수정하다보니 flyway를 적용하면 좋을 것 같다는 생각이 들어서 주말에 살짝 공부하고 적용해보려는데 괜찮을까요?(DB 형상관리가 있으면 좋겠다 라는 생각이 들어서요. 워크스페이스 관련 정리되면 살짝 봐보려고요!)
<br><br>
- Close #603 
<br><br>
=> fix: 토큰 타입 varchar(64) -> varchar(256) 로 수정

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/auth/application/dto/WorkspaceInfoDto.java, backend/src/main/java/com/pickpick/support/ExternalClient.java, backend/src/main/java/com/pickpick/support/SlackClient.java, backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java, backend/src/test/java/com/pickpick/support/FakeClient.java
botInfoDto의 이름을 WorkspaceInfoDto로 변경
<br><br>
botInfoDto의 이름을 WorkspaceInfoDto로 변경
<br><br>
채널 구독 API 수정에 함께 들어갔어야했는데 깜빡하고 커밋을 안했습니다....ㅠ
후에 작업할 테스트 관련 리팩토링에서 함께 진행할까 하다가 테스트 PR에서는 테스트 관련 내용만 수정있으면 좋을 것 같아서 따로 올립니다 ㅠㅠ
<br><br>
=> refactor: BotInfoDto의 이름을 WorkspaceInfoDto로 변경

frontend/public/index.html, frontend/src/@styles/GlobalStyle.ts
- tway_air 폰트의 preload는 제거해주고, Roboto font의 local 속성을 제거한 후 preload를 할 수 있도록 설정
- 모든 폰트에 font-display: swap 옵션을 설정
<br><br>
- Close #619 
<br><br>
=> refactor: font 설정 변경

backend/src/main/java/com/pickpick/slackevent/ui/SlackEventController.java, backend/src/main/java/com/pickpick/support/LoggingAspect.java, backend/src/main/resources/appenders/async-console-appender.xml, backend/src/main/resources/appenders/async-file-appender-info.xml, backend/src/main/resources/logback-spring.xml
로깅 처리 추가
<br><br>
controller의 메서드가 실행되는 경우 클래스명, 메서드명, 파라미터 값을 출력합니다
<br><br>
profile별로 level을 다르게 설정하고 싶었는데 기존의 로그 설정 내역을 이해할 수 없어 보류해두었습니다.
내일 봄에게 물어보고 수정하겠습니다ㅜ.ㅜ
<br><br>
=> feat: 로깅 처리 추가

backend/src/main/java/com/pickpick/exception/SlackApiCallException.java, backend/src/main/java/com/pickpick/support/SlackClient.java
슬랙 API 호출 예외 메시지 구체화
<br><br>
슬랙 API 호출 예외 메시지 구체화
<br><br>
슬랙 API 호출하는 경우 데이터가 아래와 같은 형식으로 옵니다.
```
{ 
ok: false,
error: 'missing_scope',
needed: 'channels:write',
provided: 'identify,bot:basic'
}
```
기존에는 ok를 검증한 뒤 error에 담긴 값만 로그에 찍었는데
needed, provided도 함께 찍히도록 수정했습니다.
<br><br>
=> feat: 슬랙 API 호출 예외 메시지 구체화

backend/src/main/java/com/pickpick/config/SlackProperties.java, backend/src/main/java/com/pickpick/support/SlackClient.java
로그인/워크스페이스 관련 oauth 요청시 다른 redirect uri를 보내주도록 수정
<br><br>
워크스페이스 등록 요청시 redirect uri가 로그인 요청 redirect uri로 되어있어서 문제 발생한 것 해결했씁니다.
<br><br>
<br><br>
- #633 과 관련있는 것 같은데 확실히 해결되는 것을 확인한 후 이슈는 닫겠습니다!
<br><br>
=> fix: 로그인/워크스페이스 관련 oauth 요청시 다른 redirect uri를 보내주도록 수정

backend/src/main/java/com/pickpick/support/SlackClient.java
SlackBot은 DB에 저장하지 않도록 수정
<br><br>
- SlackClient에서 member로 변환할 때 slackId가 USLACKBOT인 경우를 제외하고 저장하도록 수정했습니다.
<br><br>
<br><br>
- #633 
<br><br>
=> fix: SlackBot은 DB에 저장하지 않도록 수정

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/auth/application/dto/WorkspaceInfoDto.java, backend/src/main/java/com/pickpick/support/SlackClient.java, backend/src/test/java/com/pickpick/support/FakeClient.java
워크스페이스 등록시 oauth.v2.access를 1회만 호출하도록 수정
<br><br>
- 워크스페이스 등록 시 `methodsClient.oauthV2Access(request)`를 1회만 호출하도록 했습니다.
**기존 로직**
callWorkspaceInfo
-> oauthV2Access
findMembersByWorkspace
-> usersList
findChannelsByWorkspace
-> conversationsList
callUserToken
-> oauthV2Access
callMemberSlackId
-> usersIdentity
**수정한 로직**
callWorkspaceInfo
-> oauthV2Access
findMembersByWorkspace
-> usersList
findChannelsByWorkspace
-> conversationsList
callMemberSlackId
-> usersIdentity
<br><br>
기존 로직대로 진행하면 위의 예외가 발생했습니다.
예상하건데, 기존 로직은 `동일한 code`로 `oauthV2Access`를 2회 호출했는데, 첫번째 호출시에는 올바르게 값을 가져올 수 있었지만 두번째 호출시에는 `invalid_code` 가 발생하는걸로 보아, 한 code로 `oauthV2Access` 의 호출은 1회만 유효한 것 같습니다.
따라서 첫 호출때에 userToken도 함께 호출하게 했습니다. 
<br><br>
- Closes #633 
<br><br>
=> fix: 워크스페이스 등록시 oauth.v2.access를 1회만 호출하도록 수정

backend/src/main/java/com/pickpick/support/SlackClient.java, backend/src/main/java/com/pickpick/support/SlackFunction.java, backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java, backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
SlackClient 로직 개선
<br><br>
- request 및 exception 값 로깅
- 공통 예외 처리 분리
참고 #639 
<br><br>
=> refactor: SlackClient 로직 개선 및 로깅 추가

backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java, backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java, backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
채널이 삭제되지 않는 현상 개선
<br><br>
채널 구독이 삭제되지 않은 상태로 채널 삭제를 시도하는 경우 DataIntegrityViolationException가 발생합니다.
채널 삭제 이벤트 발생 시 메시지, 채널 구독, 채널을 삭제하도록 로직을 수정하였습니다.
<br><br>
- Close #645 
<br><br>
=> fix: 채널이 삭제되지 않는 현상 개선

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/auth/ui/AuthController.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/auth/AuthRestHandler.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java, backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
줍줍봇 최초 설치 시 로그인 로직 제거 
<br>
줍줍봇 설치 시 필요한 `channels:read / write`와 로그인 시 필요한 `identity.basic`이  한 번에 `OAuth` 요청 시 충돌합니다 
따라서 이 두 권한을 분리할 수 있도록, 설치 시 로그인 로직을 제거합니다  
- 줍줍봇 최초 설치 시 `봇 토큰` 발급 
- `봇 토큰`으로 워크스페이스 저장
- `봇 토큰`으로 워크스페이스 멤버 저장
- `봇 토큰`으로 워크스페이스 채널 저장
===== 이하 삭제 =====
- `유저 토큰`으로 로그인
<br>
=> refactor: 줍줍 최초 설치 시 로그인 로직 제거

backend/src/main/java/com/pickpick/auth/application/AuthService.java, backend/src/main/java/com/pickpick/auth/application/dto/MemberInfoDto.java, backend/src/main/java/com/pickpick/message/application/MentionReplacer.java, backend/src/main/java/com/pickpick/support/ExternalClient.java, backend/src/main/java/com/pickpick/support/SlackClient.java, backend/src/test/java/com/pickpick/support/FakeClient.java
슬랙 권한 문제 해결
<br><br>
슬랙 권한 문제 해결
- 현재 로그인 시 
1. `OAuthV2Aceess` 호출하여 user token(xoxp-xxxxx) 가져옴
2. 해당 user token으로  `user.identity` 호출하여 memberSlackId를 가져옴
- 위 과정은 `OAuthV2Aceess` 메서드 호출 한 번에 해결이 가능합니다.
- `OAuthV2Aceess` 호출하여 user token(xoxp-xxxxx)과 memberSlackId 모두가져올 수 있습니다.
<br><br>
로깅 찍었을 때 AuthedUser 내부의 id에 memberSlackId가 있는걸 확인할 수 있습니다.
보안상 가렸습니다!
+) 머지된다면 프론트에서 권한 Redirect uri 수정이 필요합니다. 호프가 가까이에 있었어서 호프에게 전달해뒀습니다!
<br><br>
- Close #669 
<br><br>
=> hotfix: 슬랙 권한 문제 해결

backend/src/main/java/com/pickpick/PickpickApplication.java, backend/src/main/java/com/pickpick/config/JpaAuditingConfig.java, backend/src/test/java/com/pickpick/support/DocsControllerTestBase.java
`@EnableJpaAuditing` 설정 클래스 분리
<br>
`@EnableJpaAuditing`이 원래 메인 클래스에 붙어있었는데요, 
`@WebMvcTest` 같이 JPA 관련 빈을 생성하지 않는 테스트를 추가하는 경우, `@MockBean`을 반복적으로 설정해줘야 합니다  
그래서 별도의 `@Configuration` 클래스로 분리했습니다 
<br>
[블로그에 해당 내용 관련 포스팅](https://hyewoncc.github.io/jpa-auditing-and-ci/)을 작성했었으니 궁금하시면 읽어보세요!  
<br>
- Close #611 
<br>
=> refactor: @EnableJpaAuditing 설정 클래스 분리

frontend/public/mockServiceWorker.js, frontend/src/components/@shared/Dropdown/index.tsx, frontend/src/components/DateDropdown/index.tsx
- Dropdown 공용 컴포넌트에 스크린리더 설명 추가 
- 기존에 Date Dropdown 컴포넌트에만 있던 드랍다운 열림/닫힘 여부를 알려주는 스크린리더 설명을 공용 Dropdown 컴포넌트로 이동했습니다!
- 따라서 모든 드랍다운류 컴포넌트에서, 해당 스크린리더 설명이 읽히도록 리팩터링했어요! 
- MSW 구동이 안되길래 찾아봣더니 mockServiceWorker.js 파일이 삭제되어있었더라구요 그래서 다시 추가해줬습니당~!
=> refactor: Dropdown 컴포넌트에 스크린리더 설명 추가 

backend/src/main/java/com/pickpick/message/application/ReminderSender.java, backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
ReminderSender에서 N+1 문제 개선
<br><br>
- Reminder 목록 조회 후 각각의 리마인더에 대해 메시지와 멤버 정보를 조회하는 SQL 발생 (1+2N개)
- deleteAll 호출 시 delete문 N개 발생
<br><br>
- deleteAll에 관한 문제는 deleteInBatch 메서드를 호출해서 해결하는 방법도 있으나, or절이 반복해서 나가기 때문에 `@Query`로 직접 선언했습니다.
<br><br>
=> fix: ReminderSender에서 N+1 문제 개선

backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java, backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java
channel subscription에서 발생하는 n+1 쿼리 해결
<br><br>
channel subscription 조회시 연관 엔티티인 channel 을 다시 조회하는 n+1 쿼리가 발생하여 이를 fetch join으로 해결했습니다
<br><br>
관련해서 노션에 정리한 내용입니다!! 👍 
https://selective-archeology-e38.notion.site/n-1-1ea4aa5f1b9f4233a94cb246bb4b9446
<br><br>
<br><br>
=> fix: channel subscription에서 발생하는 n+1 쿼리 해결

backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
ReminderRepository 에서 발생하는 3개의 쿼리를 1개로 수정
<br>
리마인더 단일 조회 시 리마인더, 메시지, 멤버를 조회하는 각각의 쿼리가 나갔습니다
`join fetch`를 적용해 쿼리 1개로 조회할 수 있도록 수정했습니다 
before
```
Hibernate: 
select
reminder0_.id as id1_5_,
reminder0_.member_id as member_i3_5_,
reminder0_.message_id as message_4_5_,
reminder0_.remind_date as remind_d2_5_ 
from
reminder reminder0_ 
where
reminder0_.message_id=? 
and reminder0_.member_id=?
Hibernate: 
select
message0_.id as id1_4_0_,
message0_.channel_id as channel_6_4_0_,
message0_.member_id as member_i7_4_0_,
message0_.modified_date as modified2_4_0_,
message0_.posted_date as posted_d3_4_0_,
message0_.slack_message_id as slack_me4_4_0_,
message0_.text as text5_4_0_ 
from
message message0_ 
where
message0_.id=?
Hibernate: 
select
member0_.id as id1_3_0_,
member0_.first_login as …
```
=> fix: ReminderRepository 에서 단일 조회 시 발생하는 쿼리 3개 -> 1개 수정
